import { Router } from 'express';
import authRoutes from './authRoutes.js';
import categoryRoutes from './categoryRoutes.js';
import supplierRoutes from './supplierRoutes.js';
import productRoutes from './productRoutes.js';
import stockRoutes from './stockRoutes.js';
import reportRoutes from './reportRoutes.js';
import userRoutes from './userRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import taskRoutes from './taskRoutes.js';
import sectionRoutes from './sectionRoutes.js';
import eslRoutes from './eslRoutes.js';
import posRoutes from './posRoutes.js';
import procurementRoutes from './procurementRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import accessRequestRoutes from './accessRequestRoutes.js';
import temporaryGrantRoutes from './temporaryGrantRoutes.js';
import permissionRoutes from './permissionRoutes.js';
import supportRoutes from './supportRoutes.js';
import warehouseRoutes from './warehouseRoutes.js';
import customerRoutes from './customerRoutes.js';
import customerAuthRoutes from './customerAuthRoutes.js';
import campaignAnalysisRoutes from './campaignAnalysisRoutes.js';
import proximityRoutes from './proximityRoutes.js';
import licenseRoutes from './licenseRoutes.js';
import licenseControlRoutes from './licenseControlRoutes.js';
import ssoRoutes from './ssoRoutes.js';
import storeLayoutRoutes from './storeLayoutRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/licenses', licenseRoutes);
router.use('/license-control', licenseControlRoutes);
router.use('/sso', ssoRoutes);
router.use('/categories', categoryRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/products', productRoutes);
router.use('/stock', stockRoutes);
router.use('/reports', reportRoutes);
router.use('/users', userRoutes);
router.use('/settings', settingsRoutes);
router.use('/tasks', taskRoutes);
router.use('/sections', sectionRoutes);
router.use('/esl', eslRoutes);
router.use('/pos', posRoutes);
router.use('/procurement', procurementRoutes);
router.use('/notifications', notificationRoutes);
router.use('/access-requests', accessRequestRoutes);
router.use('/temporary-grants', temporaryGrantRoutes);
router.use('/permissions', permissionRoutes);
router.use('/support', supportRoutes);
router.use('/warehouse', warehouseRoutes);
router.use('/customers', customerRoutes);
router.use('/customer-auth', customerAuthRoutes);
router.use('/campaign-analysis', campaignAnalysisRoutes);
router.use('/proximity', proximityRoutes);
router.use('/location-layouts', storeLayoutRoutes);

export default router;
