export const howToUseGuides = [
  {
    id: 'baslangic',
    title: 'Başlangıç',
    route: '/anasayfa',
    group: 'Genel Kullanım',
    icon: 'LayoutDashboard',
    summary: 'Shelfio ekranlarının kimler tarafından, hangi amaçla kullanılacağını anlatır.',
    purpose: 'Yeni başlayan yönetici ve mağaza personelinin doğru ekrana hızlıca gitmesini, yaptığı işlemin mağaza operasyonunu nasıl etkilediğini anlamasını sağlar.',
    capabilities: [
      'Yönetici paneli, personel mobil ekranları ve müşteri portalı arasındaki farkı anlama.',
      'Ürün, stok, sipariş, etiket, proximity, bildirim, görev ve yetki ekranlarının genel amacını öğrenme.',
      'Elektronik Etiket (ESL), Beacon ve Yakınlık Alanı kavramlarını sade şekilde ayırt etme.',
      'Yetkiye göre bazı menülerin görünmeyebileceğini bilme.',
    ],
    steps: [
      'Önce Dashboard ekranından mağazanın genel durumunu kontrol edin.',
      'Ürün ve stok değişikliği yapacaksanız Ürünler, Stok İşlemleri veya Lokasyon Yönetimi ekranlarını kullanın.',
      'Raf etiketi güncelleyecekseniz Etiket Yönetimi ekranından ürün ve cihazı kontrol edin.',
      'Müşteriye konuma bağlı bildirim göndermek için Proximity Yönetimi ekranında Yakınlık Alanı, Beacon ve Bildirim Kuralı kurun.',
      'Personel işi takip edilecekse Görev Planlama, Personel Mobil ve Bildirim Merkezi ekranlarını birlikte kullanın.',
    ],
    warnings: [
      'Ürün, fiyat, stok, etiket ve proximity işlemleri gerçek mağaza deneyimini etkiler; kaydetmeden önce seçilen ürün, cihaz ve alanı kontrol edin.',
      'Bir sayfayı göremiyorsanız hesabınızda ilgili yetki olmayabilir; erişim talebi ekranını kullanın veya yöneticinize başvurun.',
    ],
    tips: [
      'Arama kutusuna sayfa adı, işlem adı veya hata metni yazarak ilgili rehberi hızlıca bulabilirsiniz.',
      'Teknik görünen terimlerde önce ekranın açıklama metnine ve alan altındaki yardım yazısına bakın.',
    ],
    related: ['Dashboard', 'Ürünler', 'Etiket Yönetimi', 'Proximity Yönetimi', 'Görev Planlama'],
    keywords: ['başlangıç', 'yönetici', 'personel', 'müşteri', 'esl', 'elektronik etiket', 'beacon', 'yakınlık alanı'],
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    route: '/anasayfa',
    group: 'Genel Kullanım',
    icon: 'LayoutDashboard',
    summary: 'Satış, stok, görev, bildirim ve operasyon özetlerini tek ekranda gösterir.',
    purpose: 'Yöneticinin güne başlarken hangi alanda aksiyon gerektiğini görmesi için kullanılır.',
    capabilities: [
      'Günlük satış, işlem, açık görev, kritik stok ve bildirim özetlerini izleme.',
      'Operasyonel görev dağılımı, kritik uyarılar ve stok risklerini kontrol etme.',
      'Katalog/fiyat analizi, tedarik ve mal kabul durumlarını hızlıca değerlendirme.',
      'Aktivite akışından son kullanıcı işlemlerini görme.',
    ],
    steps: [
      'Sayfanın üstündeki KPI kartlarından güncel durumu okuyun.',
      'Kritik uyarı varsa önce stok, görev veya bildirim kaynağını kontrol edin.',
      'Operasyonel görev dağılımında açık, tamamlanan, geciken ve kritik görev sayılarını karşılaştırın.',
      'Günlük İşlem kartını son 24 saatte kullanıcıların yaptığı anlamlı işlem yoğunluğu olarak yorumlayın.',
      'Detay gerekiyorsa ilgili kartın gösterdiği modüle geçin.',
    ],
    warnings: [
      'Dashboard karar destek ekranıdır; kayıt düzeltmesi ilgili modülde yapılmalıdır.',
      'Sayılarda beklenmeyen artış görürseniz filtre, tarih aralığı ve ilgili modül kayıtlarını kontrol edin.',
    ],
    tips: [
      'Açık görev sayısı yalnız tamamlanmamış gerçek görevleri ifade eder.',
      'Günlük İşlem sayısı sayfa görüntüleme veya otomatik yenileme değil, kullanıcı aksiyonu odaklıdır.',
    ],
    related: ['Görev Planlama', 'Stok İşlemleri', 'Raporlar', 'Bildirim Merkezi'],
    keywords: ['dashboard', 'ana sayfa', 'kpi', 'günlük işlem', 'açık görev', 'kritik stok'],
  },
  {
    id: 'urunler',
    title: 'Ürünler',
    route: '/urunler',
    group: 'Ürün Yönetimi',
    icon: 'PackageSearch',
    summary: 'Ürün kartlarını, fiyatları, barkodları, kategori ve raf/depo yerleşim bilgilerini yönetir.',
    purpose: 'Mağazada satılan ürünlerin doğru isim, fiyat, stok ve yerleşim bilgileriyle takip edilmesini sağlar.',
    capabilities: [
      'Yeni ürün ekleme, ürün düzenleme ve ürün görüntüleme.',
      'SKU, barkod, ürün adı, marka, kategori, birim, alış fiyatı ve satış fiyatı alanlarını takip etme.',
      'Raf kodu, depo kodu, reyon stoku, depo stoku, toplam stok ve parti bilgilerini görme.',
      'Kampanya fiyatı, stok uyarısı, saklama tipi, koli/kasa içeriği ve ana tedarikçi bilgisini kontrol etme.',
      'Listelenmiş, listelenmemiş ve katalogdan gelen taslak ürünleri ayırt etme.',
    ],
    steps: [
      'Arama alanına SKU, barkod, ürün adı, kategori veya tedarikçi yazarak ürünü bulun.',
      'Kategori, tedarikçi, ürün durumu, etiket durumu, kampanya ve reyon filtrelerini kullanın.',
      'Yeni Ürün ile ürün kartını oluşturun; zorunlu kimlik, kategori ve fiyat alanlarını eksiksiz girin.',
      'Yerleşim ve planlama alanlarında raf/depo bilgilerini doğru seçin.',
      'Kaydetmeden önce satış fiyatı, barkod ve stok uyarısı alanlarını son kez kontrol edin.',
    ],
    warnings: [
      'Barkod veya SKU hatalıysa kasa, etiket ve stok işlemleri yanlış ürüne bağlanabilir.',
      'Satış fiyatı ve kampanya fiyatı müşteri ve etiket ekranlarını etkileyebilir.',
      'Taslak ürünleri tamamlamadan aktif satış akışında kullanmayın.',
    ],
    tips: [
      'Eksik Alanlar sütunu ürün kartında tamamlanması gereken bilgileri hızlıca gösterir.',
      'Parti ve SKT bilgileri stok riski, rapor ve fiyat önerilerinde önemlidir.',
    ],
    related: ['Kategoriler', 'Stok İşlemleri', 'Etiket Yönetimi', 'Kampanya Yönetimi'],
    keywords: ['ürün', 'sku', 'barkod', 'fiyat', 'stok', 'parti', 'raf', 'depo'],
  },
  {
    id: 'kategoriler',
    title: 'Kategoriler',
    route: '/kategoriler',
    group: 'Ürün Yönetimi',
    icon: 'Tags',
    summary: 'Ürünlerin ana ve alt kategori düzenini yönetir.',
    purpose: 'Ürünlerin arama, raporlama, müşteri portalı ve fiyat analizlerinde doğru gruplandırılmasını sağlar.',
    capabilities: [
      'Kategori oluşturma, düzenleme ve pasifleştirme.',
      'Kategori adını, kodunu ve üst kategori bağlantısını takip etme.',
      'Ürünleri doğru kategori altında listeleme.',
      'Kategori bazlı filtre ve raporların sağlıklı çalışmasını destekleme.',
    ],
    steps: [
      'Yeni kategori eklerken kısa, anlaşılır ve mağaza diline uygun bir ad kullanın.',
      'Alt kategori oluşturuyorsanız doğru üst kategoriyi seçin.',
      'Kategori silme veya pasifleştirme öncesi bağlı ürünleri kontrol edin.',
      'Ürün ekranında kategori filtresiyle değişikliğin doğru göründüğünü doğrulayın.',
    ],
    warnings: [
      'Kategori değişikliği ürün listesi, müşteri portalı ve rapor filtrelerini etkiler.',
      'Benzer isimli kategoriler personel ve müşteri tarafında karışıklık yaratabilir.',
    ],
    tips: [
      'Kategori adlarını reyon düzeninizle uyumlu tutmak ürün bulmayı kolaylaştırır.',
      'Kampanya ve fiyat analizlerinde kategori seçimi sık kullanıldığı için kategori ağacını sade tutun.',
    ],
    related: ['Ürünler', 'Fiyat & Talep Analizi', 'Müşteri Portalı'],
    keywords: ['kategori', 'alt kategori', 'ürün sınıflama'],
  },
  {
    id: 'tedarikciler',
    title: 'Tedarikçiler',
    route: '/tedarikciler',
    group: 'Tedarik ve Satın Alma',
    icon: 'Truck',
    summary: 'Tedarikçi firmaları, iletişim bilgilerini ve ürün bağlantılarını yönetir.',
    purpose: 'Satın alma, sipariş önerisi ve katalog karşılaştırma süreçlerinde doğru tedarikçi bilgisinin kullanılmasını sağlar.',
    capabilities: [
      'Tedarikçi ekleme, düzenleme ve durumunu takip etme.',
      'Tedarikçiye bağlı ürünleri ve satın alma koşullarını kontrol etme.',
      'Katalog veya ürün eşleşmelerinde tedarikçi bilgisini kullanma.',
      'Sipariş oluşturma ve takip ekranlarına doğru tedarikçi verisi sağlama.',
    ],
    steps: [
      'Tedarikçi adını ve iletişim bilgilerini eksiksiz girin.',
      'Aktif/pasif durumunu satın alma operasyonuna göre düzenleyin.',
      'Tedarikçiye bağlı ürünlerde birim, koli ve fiyat bilgilerinin doğru olduğundan emin olun.',
      'Sipariş oluştururken doğru tedarikçiyi seçtiğinizi kontrol edin.',
    ],
    warnings: [
      'Yanlış tedarikçi seçimi siparişin hatalı firmaya hazırlanmasına neden olabilir.',
      'Pasif tedarikçi bilgileri öneri ve sipariş ekranlarında beklediğiniz gibi görünmeyebilir.',
    ],
    tips: [
      'Tedarikçi adlarını resmi firma adıyla tutmak sipariş ve rapor okumayı kolaylaştırır.',
      'Ürün eşleşmeleri düzgünse sipariş önerileri daha anlaşılır olur.',
    ],
    related: ['Eşleşmeler', 'Sipariş Oluştur', 'Sipariş Takibi', 'Tedarikçi Ürünleri'],
    keywords: ['tedarikçi', 'firma', 'satın alma', 'sipariş'],
  },
  {
    id: 'eslesmeler',
    title: 'Eşleşmeler',
    route: '/eslesmeler',
    group: 'Ürün Yönetimi',
    icon: 'Link2',
    summary: 'Ürünlerin tedarikçi, reyon ve depo bağlantılarını takip etmek için kullanılır.',
    purpose: 'Aynı ürünün mağaza, depo ve tedarikçi tarafında doğru kayıtlarla eşleşmesini sağlar.',
    capabilities: [
      'Ürün-tedarikçi bağlantılarını kontrol etme.',
      'Reyon ve depo lokasyon eşleşmelerini görme veya düzenleme.',
      'Tedarikçi ürün kodu, barkod ve fiyat bilgisi üzerinden karar verme.',
      'Çakışma veya eksik eşleşme risklerini fark etme.',
    ],
    steps: [
      'Eşleştirmek istediğiniz ürünü arayın.',
      'Tedarikçi tarafındaki kod, barkod ve fiyat bilgisini kontrol edin.',
      'Reyon veya depo eşleşmesi yapılacaksa doğru lokasyonu seçin.',
      'Kaydetmeden önce ürün adı ve kodların aynı ürünü işaret ettiğini doğrulayın.',
    ],
    warnings: [
      'Yanlış eşleşme sipariş, stok ve raf yerleşim süreçlerini zincirleme etkileyebilir.',
      'Barkodu aynı görünen ama farklı ürün olan kayıtları dikkatle ayırın.',
    ],
    tips: [
      'Kararsız kaldığınızda ürün detayını açıp marka, birim ve koli içeriğini karşılaştırın.',
      'Eşleşmeler temiz olduğunda tedarik ve fiyat analizleri daha güvenilir olur.',
    ],
    related: ['Ürünler', 'Tedarikçiler', 'Lokasyon Yönetimi', 'Sipariş Oluştur'],
    keywords: ['eşleşme', 'tedarikçi ürün kodu', 'depo eşleşme', 'reyon eşleşme'],
  },
  {
    id: 'lokasyon-yonetimi',
    title: 'Lokasyon Yönetimi',
    route: '/lokasyon-yonetimi',
    group: 'Ürün Yönetimi',
    icon: 'Monitor',
    summary: 'Reyon, raf, depo ve mağaza içi yerleşim alanlarını yönetir.',
    purpose: 'Ürünlerin fiziksel olarak nerede bulunduğunu, personelin nereden alıp nereye yerleştireceğini netleştirir.',
    capabilities: [
      'Reyon, raf ve depo lokasyonlarını listeleme.',
      'Lokasyon kodlarıyla ürün yerleşimini takip etme.',
      'Aktif/pasif lokasyonları ayırma.',
      'Personel lokasyon ve reyon besleme işlerinde doğru yer bilgisini sağlama.',
    ],
    steps: [
      'Yeni lokasyon oluştururken mağaza içinde herkesin anlayacağı bir ad verin.',
      'Raf, kat, taraf veya depo kodu gibi alanları fiziksel yerleşime uygun doldurun.',
      'Ürün veya eşleşme ekranlarında bu lokasyonların doğru kullanıldığını kontrol edin.',
      'Kullanılmayan alanları pasifleştirerek yanlış seçim riskini azaltın.',
    ],
    warnings: [
      'Lokasyon kodu değişirse ürün listeleri, görevler ve personel saha işlemleri etkilenebilir.',
      'Aynı fiziksel alan için birden fazla benzer kod oluşturmak karışıklık yaratır.',
    ],
    tips: [
      'Kodları kısa, tutarlı ve mağaza planına uygun seçin.',
      'Proximity Yakınlık Alanı ile reyon/lokasyon aynı şey değildir; biri fiziksel ürün yeri, diğeri müşteri yakınlık bölgesidir.',
    ],
    related: ['Ürünler', 'Stok İşlemleri', 'Proximity Yönetimi', 'Personel Mobil'],
    keywords: ['lokasyon', 'reyon', 'raf', 'depo', 'yerleşim'],
  },
  {
    id: 'stok-islemleri',
    title: 'Stok İşlemleri',
    route: '/stok-islemleri',
    group: 'Ürün Yönetimi',
    icon: 'Boxes',
    summary: 'Stok giriş, çıkış, düzeltme, transfer ve parti hareketlerini izler.',
    purpose: 'Ürün miktarlarının reyon ve depoda doğru tutulmasını, hareket geçmişinin takip edilebilmesini sağlar.',
    capabilities: [
      'Stok hareketlerini listeleme ve filtreleme.',
      'Giriş, çıkış, düzeltme ve transfer hareketlerini ayırt etme.',
      'Ürün, miktar, neden, referans, kullanıcı ve tarih bilgisini takip etme.',
      'Parti, lot ve SKT bilgisi olan ürünlerde hareketin hangi partiye ait olduğunu görme.',
    ],
    steps: [
      'Ürün veya barkod aramasıyla hareketini incelemek istediğiniz kaydı bulun.',
      'Hareket tipini kontrol edin: giriş stok artırır, çıkış azaltır, transfer yer değiştirir, düzeltme sayım farkını kapatır.',
      'Miktar ve neden alanlarını birlikte okuyun; tek başına miktar her zaman yeterli açıklama vermez.',
      'Hatalı hareket şüphesinde ilgili ürünün toplam stok, reyon stok ve depo stok değerlerini karşılaştırın.',
    ],
    warnings: [
      'Stok düzeltmesi gerçek stok bilgisini değiştirir; sayım veya teslim belgesi olmadan rastgele düzeltme yapmayın.',
      'Parti/SKT takibi olan ürünlerde yanlış parti seçimi rapor ve uyarıları bozabilir.',
    ],
    tips: [
      'Referans numarası aynı işlemin birden fazla satırını bağlamanıza yardımcı olur.',
      'Stok sorunu görürseniz önce son hareketleri, sonra ürün detayındaki stok özetini kontrol edin.',
    ],
    related: ['Ürünler', 'Depo Transfer Talepleri', 'Personel Sayım', 'Raporlar'],
    keywords: ['stok', 'hareket', 'giriş', 'çıkış', 'transfer', 'sayım', 'parti', 'skt'],
  },
  {
    id: 'depo-transfer-talepleri',
    title: 'Depo Transfer Talepleri',
    route: '/depo-transfer-talepleri',
    group: 'Ürün Yönetimi',
    icon: 'Boxes',
    summary: 'Depodan reyona ürün çıkarma veya transfer isteklerini takip eder.',
    purpose: 'Personelin reyon besleme taleplerini yönetici/depo ekibi tarafından düzenli şekilde karşılamasını sağlar.',
    capabilities: [
      'Bekleyen, onaylanan, işlemde, tamamlanan, reddedilen ve iptal edilen talepleri görme.',
      'SKU, barkod, ürün, istenen miktar, depo stoku, öncelik ve not alanlarını takip etme.',
      'Talep durumunu uygun akışa göre güncelleme.',
      'Tamamlanan talepleri arşivleme veya sonuç mesajını yorumlama.',
    ],
    steps: [
      'Bekleyen talepleri öncelik ve talep zamanı sırasına göre inceleyin.',
      'Depo stoku yeterliyse talebi onaylayın veya işlem durumuna alın.',
      'Ürün reyon alanına çıkarıldığında tamamlandı durumuna taşıyın.',
      'Eksik stok, yanlış ürün veya uygun olmayan talep varsa reddetme/iptal nedenini notla açıklayın.',
    ],
    warnings: [
      'İşlemdeki kayıtlar bazı durumlarda iptal edilemeyebilir; önce mevcut durumu okuyun.',
      'Depo stoku yetersizse transfer tamamlandı yapılmamalıdır.',
    ],
    tips: [
      'Not alanı saha ekibiyle iletişim için değerlidir; kısa ama açıklayıcı yazın.',
      'Talep kartlarını durum kolonlarına göre okumak operasyon sırasını netleştirir.',
    ],
    related: ['Stok İşlemleri', 'Personel Mobil', 'Ürünler'],
    keywords: ['depo transfer', 'reyon besleme', 'talep', 'öncelik'],
  },
  {
    id: 'barkod-islemleri',
    title: 'Barkod İşlemleri',
    route: '/barkod-islemleri',
    group: 'Ürün Yönetimi',
    icon: 'ScanBarcode',
    summary: 'Barkod üzerinden ürün bulma ve hızlı ürün kontrolü yapmak için kullanılır.',
    purpose: 'Personelin rafta veya depoda ürün kimliğini hızlı doğrulamasına yardımcı olur.',
    capabilities: [
      'Barkod okutarak veya yazarak ürün arama.',
      'Ürün adı, SKU, fiyat ve stok gibi temel bilgileri kontrol etme.',
      'Yanlış barkod veya eksik ürün durumunu fark etme.',
      'Ürün kartına geçip detayları düzenleme ihtiyacını belirleme.',
    ],
    steps: [
      'Barkodu okutun veya barkod numarasını arama alanına yazın.',
      'Bulunan ürünün adını, fiyatını ve stok bilgisini kontrol edin.',
      'Ürün bulunamazsa barkodun doğru okunduğundan emin olun.',
      'Gerekirse Ürünler ekranına geçip barkod bilgisini düzeltin.',
    ],
    warnings: [
      'Yanlış barkod müşteriye yanlış fiyat veya ürün bilgisi gösterilmesine neden olabilir.',
      'Barkod bulunamadığında hemen yeni ürün açmadan önce benzer ürünleri arayın.',
    ],
    tips: [
      'Barkod kontrolünü özellikle yeni ürün, fiyat değişimi ve etiket gönderimi öncesinde kullanın.',
      'Aynı barkod birden fazla üründe görünüyorsa yöneticinizle kontrol edin.',
    ],
    related: ['Ürünler', 'Etiket Yönetimi', 'POS / Kasa'],
    keywords: ['barkod', 'sku', 'ürün arama', 'etiket'],
  },
  {
    id: 'etiket-yonetimi',
    title: 'Etiket Yönetimi',
    route: '/etiket-yonetimi',
    group: 'Etiket ve Raf',
    icon: 'Monitor',
    summary: 'Ürün fiyat ve kampanya bilgisini Elektronik Etiket (ESL) cihazlarına gönderir.',
    purpose: 'Raf üzerindeki elektronik etikette doğru ürün, fiyat, kampanya ve barkod bilgisinin görünmesini sağlar.',
    capabilities: [
      'Ürün seçip elektronik etiket cihazına gönderme.',
      'Etiket önizlemesinde ürün adı, fiyat, kampanya ve barkod bilgisini kontrol etme.',
      'Etiketleri yenileme, yeniden gönderme ve güncelleme geçmişini inceleme.',
      'Cihazın online/heartbeat durumunu ve mevcut etikette hangi ürünün bağlı olduğunu görme.',
      'Gerekirse mevcut etiket bağlantısını temizleme.',
    ],
    steps: [
      'Etiket Yönetimi sayfasında güncellenecek ürünü arayın ve seçin.',
      'Doğru elektronik etiket cihazını seçin; cihaz adı ve mevcut ürün bilgisini kontrol edin.',
      'Önizlemede fiyat, kampanya ve barkod bilgisinin doğru olduğundan emin olun.',
      'Etikete Gönder veya Etiketi Yeniden Gönder aksiyonunu kullanın.',
      'Gönderimden sonra geçmiş, cihaz durumu ve etiket üzerindeki güncel ürün bilgisini kontrol edin.',
    ],
    warnings: [
      'Yanlış cihaz seçilirse farklı raftaki etiket güncellenebilir.',
      'Cihaz offline ise panelde işlem görülse bile fiziksel etiket hemen değişmeyebilir.',
      'Proximity ürün bildirimi, beacon ile bağlı elektronik etiketteki ürünü okuyabilir; etiket-ürün bağlantısını dikkatli tutun.',
    ],
    tips: [
      'Önizleme alanını son kontrol noktası olarak kullanın.',
      'Heartbeat eskiyse cihazın bağlantısını veya güç durumunu kontrol edin.',
    ],
    related: ['Ürünler', 'Proximity Yönetimi', 'Kampanya Yönetimi'],
    keywords: ['etiket', 'esl', 'elektronik etiket', 'heartbeat', 'current label', 'etikete gönder'],
  },
  {
    id: 'proximity-yonetimi',
    title: 'Proximity Yönetimi',
    route: '/proximity-yonetimi',
    group: 'Yakınlık ve Beacon',
    icon: 'MapPinned',
    summary: 'Beacon cihazları, Yakınlık Alanları ve müşteriye gösterilecek konum bazlı bildirim kurallarını yönetir.',
    purpose: 'Müşteri mağazada belirli bir reyon veya kampanya alanına yaklaştığında doğru bildirimin oluşması için gerekli cihaz, alan, etiket ve kural bağlantılarını kurar.',
    capabilities: [
      'Beacon cihazlarını ekleme, düzenleme ve aktif/pasif yapma.',
      'Yakınlık Alanı oluşturma ve bu alanı reyon/bölümle ilişkilendirme.',
      'Beacon cihazını reyon, Yakınlık Alanı ve Elektronik Etiket (ESL) ile eşleştirme.',
      'Bildirim kuralı oluşturarak bildirimin ne zaman, kime ve hangi içerikle gösterileceğini belirleme.',
      'Event Logları ile telefondan gelen beacon algılama olaylarını izleme.',
      'Teslimat / Cooldown ekranından bildirimin gösterilip gösterilmediğini, engellendiyse nedenini okuma.',
    ],
    steps: [
      'Önce Yakınlık Alanları sekmesinde mağazadaki anlamlı alanı oluşturun. Örneğin Süt Reyonu Giriş Alanı.',
      'Beacon Cihazları sekmesinde Yeni Beacon Ekle ile cihazı tanımlayın. Beacon, telefonların yakındaki alanı anlamasına yardımcı olan küçük BLE sinyal cihazıdır.',
      'Beacon formunda Cihaz Adı panelde görünen isimdir; Cihaz Kodu sistemde cihazı ayırt eden kısa koddur.',
      'Bağlı Etiket / ESL Cihazı, bu beacon yakınındaki rafta hangi elektronik etiketin olduğunu belirtir. Ürün bazlı indirim bildirimi için bu bağlantı önemlidir.',
      'Eşleşen Reyon, cihazın fiziksel olarak hangi reyonda olduğunu gösterir. Eşleşen Yakınlık Alanı ise müşterinin hangi alanda sayılacağını belirler.',
      'Durum Aktif ise beacon bildirim senaryolarında kullanılabilir; Pasif ise kayıt durur ama algılama için kullanılmaz.',
      'Gelişmiş ayarlardaki UUID, Major ve Minor cihazın teknik kimlik bilgileridir; cihaz kurulumunda verilen değerlerle uyumlu olmalıdır.',
      'Yakınlık Alanı formunda Alan Adı kullanıcıların göreceği isimdir; Alan Kodu sistem içi kısa koddur.',
      'Alan Tipi reyon, giriş, kampanya, kasa yakını veya genel alan gibi mağaza içi anlamı belirtir.',
      'Bağlı Reyon / Bölüm seçilirse alanın hangi reyonla ilişkili olduğu daha net takip edilir.',
      'Bildirim Kuralları sekmesinde Yeni Bildirim Kuralı Ekle ile müşteriye gösterilecek mesajı tanımlayın.',
      'Bildirim Kime Gösterilsin alanı hedef kullanıcıyı belirtir; mevcut akış müşteri bildirimleri içindir.',
      'Bildirim Ne Zaman Çıksın alanı tetikleyicidir: alana girişte, alandan çıkışta veya alanda belirli süre kalınca bildirimin çalışmasını anlatır.',
      'Hangi Yakınlık Alanında seçimi kuralın tüm alanlarda mı yoksa sadece belirli bir alanda mı çalışacağını belirler.',
      'Hangi Beacon seçimi isteğe bağlıdır; seçilirse kural yalnız o beacon için daraltılır, boş bırakılırsa tüm uygun beaconlar için geçerli olabilir.',
      'Bildirim Başlığı müşterinin ilk gördüğü kısa başlıktır. Bildirim Mesajı başlığın altındaki açıklamadır.',
      'Buton Yazısı müşterinin dokunacağı aksiyon metnidir. Açılacak Sayfa, butona basınca müşteri portalında gidilecek sayfadır.',
      'Tekrar Bekleme Süresi, aynı müşteriye aynı kuralın hemen tekrar gösterilmesini engeller. Ziyaret Başına Limit, bir ziyarette kaç kez gösterileceğini sınırlar.',
      'Kurulumdan sonra customer uygulamasıyla beacon yakınına gidin, önce Event Logları, sonra Teslimat / Cooldown sonucunu kontrol edin.',
    ],
    warnings: [
      'Müşteriye bildirim gitmesi için beacon aktif olmalı, Yakınlık Alanı aktif olmalı, kural aktif olmalı ve müşteri uygulaması uygun izinlerle çalışmalıdır.',
      'Ürün indirim bildirimi için beacon üzerinde bağlı elektronik etiket olmalı, etikette bir ürün bulunmalı ve üründe aktif indirim/kampanya olmalıdır.',
      'Etiketteki ürün değişirse sistem sonraki proximity olaylarında yeni bağlı ürünü dikkate alır; eski ürün için bildirim beklemeyin.',
      'Aynı ürün için bildirim hemen tekrar gelmeyebilir; ürün bazlı tekrar engeli ve kural cooldown süresi bunu bilinçli olarak sınırlar.',
      'UUID, Major ve Minor değerlerini yanlış girerseniz telefonun algıladığı beacon sistemdeki kayıtla eşleşmeyebilir.',
    ],
    tips: [
      'Event Log, telefondan sisteme gelen yakınlık olayını gösterir: hangi beacon, hangi alan, hangi müşteri ve hangi sonuç.',
      'Teslimat / Cooldown ekranı bildirimin gösterildi mi, atlandı mı, neden atlandı mı sorularını cevaplar.',
      'UNKNOWN_BEACON: Telefon bir beacon gördü ama sistemde eşleşen kayıt bulunamadı. Cihaz kodu, UUID, Major ve Minor değerlerini kontrol edin.',
      'NO_LINKED_ESL_DEVICE: Beacon var ama elektronik etiket bağlantısı yok. Beacon formundan Bağlı Etiket / ESL Cihazı seçin.',
      'NO_LABEL_PRODUCT: Beacon etiketle bağlı ama etikette ürün yok. Etiket Yönetimi ekranında etikete ürün gönderin.',
      'NO_ACTIVE_DISCOUNT_FOR_LABEL_PRODUCT: Etiketteki üründe aktif indirim bulunmadı. Kampanya veya ürün fiyatını kontrol edin.',
      'PRODUCT_DISCOUNT_ALREADY_NOTIFIED_12H: Aynı müşteriye aynı ürün için yakın zamanda bildirim gönderildi. Bu tekrar engeli normaldir.',
      'Test sırası: etiket ürünü doğru mu, beacon aktif mi, Yakınlık Alanı aktif mi, kural aktif mi, Event Log oluştu mu, Delivery Log ne diyor?',
    ],
    related: ['Etiket Yönetimi', 'Kampanya Yönetimi', 'Müşteri Portalı', 'Bildirim Merkezi'],
    keywords: ['proximity', 'beacon', 'yakınlık alanı', 'zone', 'event log', 'delivery log', 'cooldown', 'UNKNOWN_BEACON', 'NO_LINKED_ESL_DEVICE', 'NO_LABEL_PRODUCT', 'NO_ACTIVE_DISCOUNT_FOR_LABEL_PRODUCT', 'PRODUCT_DISCOUNT_ALREADY_NOTIFIED_12H'],
  },
  {
    id: 'fiyat-talep-analizi',
    title: 'Fiyat & Talep Analizi',
    route: '/fiyat-talep-analizi',
    group: 'Talep ve Analiz',
    icon: 'BrainCircuit',
    summary: 'Fiyat, talep, stok riski ve kampanya önerilerini analiz eder.',
    purpose: 'Yöneticinin hangi ürünlerde indirim, fiyat koruma veya fiyat güncellemesi gerektiğini anlamasına yardımcı olur.',
    capabilities: [
      'SKT yaklaşan, yavaş satış, aşırı stok ve yüksek marj potansiyeli gibi hazır analizleri kullanma.',
      'Kategori, ürün veya fiyat aralığı bazlı değerlendirme yapma.',
      'Zam, indirim veya sabit fiyat senaryolarını simüle etme.',
      'Marj riski, beklenen brüt kar ve önerilen satış fiyatını inceleme.',
      'Uygun ürünleri Kampanya Yönetimi akışına aktarma.',
    ],
    steps: [
      'Önce hazır analiz kartlarından mağaza ihtiyacına uygun olanı seçin.',
      'Risk, SKT, satış hızı ve öneri filtreleriyle listeyi daraltın.',
      'Ürün satırında mevcut fiyat, önerilen fiyat, beklenen marj ve risk nedenini okuyun.',
      'Toplu işlem yapacaksanız seçili ürünlerin zarar veya düşük marj riski taşımadığını kontrol edin.',
      'Kampanyaya Ekle aksiyonunu kullanmadan önce kampanya süresi ve hedef ürünleri tekrar gözden geçirin.',
    ],
    warnings: [
      'Analiz öneri üretir; nihai fiyat kararını mağaza stratejisi ve maliyet bilgisiyle birlikte verin.',
      'Maliyet altı veya düşük marj uyarısı olan ürünlerde kampanya açmadan önce yöneticiden onay alın.',
    ],
    tips: [
      'SKT yaklaşan ve aşırı stok filtreleri hızlı aksiyon gerektiren ürünleri bulmak için etkilidir.',
      'Aynı ürünü hem normal fiyat hem kampanya fiyatı açısından kontrol edin.',
    ],
    related: ['Kampanya Yönetimi', 'Ürünler', 'Raporlar'],
    keywords: ['fiyat analizi', 'talep analizi', 'indirim önerisi', 'marj', 'skt', 'kampanya'],
  },
  {
    id: 'kampanya-yonetimi',
    title: 'Kampanya Yönetimi',
    route: '/kampanya-yonetimi',
    group: 'Talep ve Analiz',
    icon: 'Megaphone',
    summary: 'Ürün kampanyalarını ve kampanya fiyatlarını yönetir.',
    purpose: 'Müşteri portalı, ürün fiyatı ve elektronik etiketlerde doğru kampanya bilgisinin görünmesini sağlar.',
    capabilities: [
      'Kampanya oluşturma, düzenleme, takip etme ve sonlandırma.',
      'Kampanya ürünü, tarih aralığı, kampanya fiyatı ve açıklamasını yönetme.',
      'Fiyat & Talep Analizi ekranından gelen önerileri kampanyaya dönüştürme.',
      'Aktif kampanyaların ürün ve etiket tarafındaki etkisini kontrol etme.',
    ],
    steps: [
      'Kampanya oluştururken ürünleri ve geçerlilik tarihlerini seçin.',
      'Kampanya fiyatının maliyet ve marj açısından uygun olduğunu kontrol edin.',
      'Açıklamayı müşteri ve personel tarafından anlaşılacak şekilde yazın.',
      'Aktif olduktan sonra Ürünler ve Etiket Yönetimi ekranlarında kampanya fiyatının doğru göründüğünü kontrol edin.',
    ],
    warnings: [
      'Yanlış tarih aralığı kampanyanın erken başlamasına veya geç bitmesine neden olabilir.',
      'Kampanya fiyatı etiket ve müşteri bildirimlerini etkileyebilir.',
    ],
    tips: [
      'Kısa süreli kampanyalarda bitiş tarihini özellikle kontrol edin.',
      'Proximity ürün bildirimi için kampanyalı ürünün bağlı elektronik etikette görünmesi gerekir.',
    ],
    related: ['Fiyat & Talep Analizi', 'Etiket Yönetimi', 'Proximity Yönetimi'],
    keywords: ['kampanya', 'indirim', 'kampanya fiyatı', 'müşteri bildirimi'],
  },
  {
    id: 'siparis-onerileri',
    title: 'Sipariş Önerileri',
    route: '/siparis-onerileri',
    group: 'Talep ve Analiz',
    icon: 'Sparkles',
    summary: 'Stok, satış ve tedarik sinyallerine göre satın alma önerilerini gösterir.',
    purpose: 'Eksik veya riskli ürünler için yöneticinin sipariş kararını daha hızlı vermesini sağlar.',
    capabilities: [
      'Önerilen ürünleri, miktarları, risk seviyelerini ve tedarikçi bilgisini inceleme.',
      'Filtreleme, gruplama ve toplu aksiyonlarla önerileri yönetme.',
      'Uygun önerileri satın alma siparişine dönüştürme.',
      'Uyarı ve boş durum mesajlarından neden öneri oluşmadığını anlama.',
    ],
    steps: [
      'Öneri listesini risk ve tedarikçi bilgisine göre inceleyin.',
      'Ürün stokunu, satış hızını ve önerilen miktarı karşılaştırın.',
      'Aynı tedarikçiye ait ürünleri birlikte değerlendirerek sipariş hazırlayın.',
      'Öneriyi siparişe dönüştürmeden önce tedarikçi ve miktarı kontrol edin.',
    ],
    warnings: [
      'Öneri otomatik hesaplanır; gerçek mağaza ihtiyacı ve kampanya planı ayrıca değerlendirilmelidir.',
      'Tedarikçi eşleşmesi eksikse öneri siparişe doğru şekilde dönüşmeyebilir.',
    ],
    tips: [
      'Boş liste her zaman hata değildir; filtreler veya stok durumu öneri üretmemiş olabilir.',
      'Yüksek riskli ürünleri önce değerlendirin.',
    ],
    related: ['Sipariş Oluştur', 'Sipariş Takibi', 'Tedarikçiler', 'Ürünler'],
    keywords: ['sipariş önerisi', 'tedarik', 'stok riski', 'otomatik öneri'],
  },
  {
    id: 'siparis-olustur',
    title: 'Sipariş Oluştur',
    route: '/siparis-olustur',
    group: 'Tedarik ve Satın Alma',
    icon: 'Wallet',
    summary: 'Tedarikçi ürünleri ve katalog bilgileriyle satın alma siparişi hazırlar.',
    purpose: 'Mağaza ihtiyacına göre doğru tedarikçiden doğru ürünlerin sipariş edilmesini sağlar.',
    capabilities: [
      'Tedarikçi ürünlerini listeleme ve karşılaştırma.',
      'Katalogdan gelen ürünleri, fiyat farklarını ve eşleşme durumlarını inceleme.',
      'Sipariş kalemlerini hazırlama ve sipariş oluşturma.',
      'Taslak, riskli veya onay bekleyen katalog satırlarını ayırt etme.',
    ],
    steps: [
      'Tedarikçiyi ve siparişe eklenecek ürünleri seçin.',
      'Ürün kodu, barkod, koli içeriği ve fiyat bilgisini kontrol edin.',
      'Miktarları girerken mevcut stok ve sipariş önerilerini dikkate alın.',
      'Siparişi oluşturmadan önce toplam tutar, kalem sayısı ve teslim bilgilerini kontrol edin.',
    ],
    warnings: [
      'Yanlış tedarikçi veya ürün kodu seçimi siparişin hatalı hazırlanmasına neden olur.',
      'Katalogdan gelen fiyat değişikliklerini onaylamadan siparişe yansıtmayın.',
    ],
    tips: [
      'Aynı tedarikçiye ait ürünleri birlikte sipariş etmek takip etmeyi kolaylaştırır.',
      'Katalog eşleşme risklerini siparişten önce çözmek daha güvenlidir.',
    ],
    related: ['Tedarikçiler', 'Sipariş Önerileri', 'Sipariş Takibi', 'Eşleşmeler'],
    keywords: ['sipariş oluştur', 'tedarikçi ürünleri', 'katalog', 'satın alma'],
  },
  {
    id: 'siparis-takibi',
    title: 'Sipariş Takibi',
    route: '/siparis-takibi',
    group: 'Tedarik ve Satın Alma',
    icon: 'Receipt',
    summary: 'Satın alma siparişlerinin onay, sevkiyat, mal kabul ve arşiv akışını izler.',
    purpose: 'Siparişin hangi aşamada olduğunu, ne zaman depoya ulaştığını ve stok girişinin tamamlanıp tamamlanmadığını takip eder.',
    capabilities: [
      'Aktif, onay bekleyen, depoya ulaşan, stok girişi bekleyen ve arşiv siparişlerini görme.',
      'Sipariş durumunu uygun geçişlerle güncelleme.',
      'Mal kabul kararı verme ve sipariş detayını inceleme.',
      'Sipariş PDF/dışa aktarım aksiyonlarını kullanma.',
    ],
    steps: [
      'Sipariş listesini durum, tedarikçi, tarih ve tutar filtreleriyle daraltın.',
      'Sipariş detayında kalemleri, miktarları ve teslim bilgisini kontrol edin.',
      'Uygun aşamada durum güncellemesi yapın; sistem izin vermiyorsa akışta doğru adımda olmayabilirsiniz.',
      'Ürün geldiğinde mal kabul ekranından kabul kararını verin.',
      'Tamamlanan veya iptal edilen siparişleri arşiv alanından takip edin.',
    ],
    warnings: [
      'Durum geçişleri sıraya bağlıdır; her sipariş her adıma doğrudan taşınamaz.',
      'Mal kabul yanlış yapılırsa stok girişi ve tedarik raporları etkilenebilir.',
    ],
    tips: [
      'Geciken teslimatları tahmini teslim tarihine göre kontrol edin.',
      'Detay ekranı siparişin neden beklediğini anlamak için en güvenli yerdir.',
    ],
    related: ['Sipariş Oluştur', 'Stok İşlemleri', 'Raporlar'],
    keywords: ['sipariş takibi', 'mal kabul', 'onay', 'tedarik', 'arşiv'],
  },
  {
    id: 'raporlar',
    title: 'Raporlar',
    route: '/raporlar',
    group: 'Raporlama',
    icon: 'BarChart3',
    summary: 'Stok, satış, satın alma, görev ve operasyon verilerini raporlar.',
    purpose: 'Yöneticinin karar alırken geçmiş ve güncel operasyon verilerini birlikte görmesini sağlar.',
    capabilities: [
      'Stok, satış, ürün, tedarik, görev ve bildirim raporlarını inceleme.',
      'Filtre ve tarih aralıklarıyla veriyi daraltma.',
      'Kritik ürün, düşük stok, geciken sipariş ve operasyon yoğunluğu gibi sonuçları yorumlama.',
      'Dashboard özetlerinin detayına inme.',
    ],
    steps: [
      'Rapor türünü ve tarih aralığını seçin.',
      'Filtreleri uygulayarak yalnız ilgili ürün, kategori veya tedarikçiyi görüntüleyin.',
      'Tablodaki sayıların hangi dönem ve filtreyle hesaplandığını kontrol edin.',
      'Gerekirse ilgili işlem ekranına geçip düzeltme veya aksiyon alın.',
    ],
    warnings: [
      'Yanlış tarih aralığı raporu yanıltıcı gösterebilir.',
      'Rapor ekranı çoğunlukla okuma ve analiz amaçlıdır; düzeltme ilgili modülden yapılmalıdır.',
    ],
    tips: [
      'Dashboard’da gördüğünüz bir uyarının kaynağını Raporlar ekranında detaylandırabilirsiniz.',
      'Filtreleri temizleyerek genel durumla karşılaştırma yapın.',
    ],
    related: ['Dashboard', 'Ürünler', 'Stok İşlemleri', 'Sipariş Takibi'],
    keywords: ['rapor', 'analiz', 'satış', 'stok', 'tedarik', 'görev'],
  },
  {
    id: 'gorev-planlama',
    title: 'Görev Planlama',
    route: '/gorev-planlama',
    group: 'Operasyon',
    icon: 'ClipboardList',
    summary: 'Personel görevlerini oluşturur, atar ve durumlarını takip eder.',
    purpose: 'Mağaza içi işlerin kime atandığını, ne zaman tamamlanması gerektiğini ve hangi durumda olduğunu görünür kılar.',
    capabilities: [
      'Yeni görev oluşturma ve personel atama.',
      'Öncelik, durum, başlangıç tarihi, son tarih ve oluşturan bilgilerini takip etme.',
      'Bekliyor, Devam Ediyor ve Tamamlandı durumlarını yönetme.',
      'Görev silme veya güncelleme aksiyonlarını kullanma.',
    ],
    steps: [
      'Yeni görev oluştururken başlığı açık yazın; personelin sahada ne yapacağını anlaması gerekir.',
      'Atanan kişiyi, önceliği ve son tarihi seçin.',
      'Görev başladığında Devam Ediyor, bittiğinde Tamamlandı durumuna alın.',
      'Geciken görevleri son tarih ve öncelik bilgisiyle takip edin.',
    ],
    warnings: [
      'Tamamlanan görevler açık görev sayısına dahil edilmez.',
      'Yanlış personele atanan görev saha operasyonunda gecikmeye neden olabilir.',
    ],
    tips: [
      'Görev başlığında ürün, reyon veya işlem adını yazmak personelin işi hızlı bulmasını sağlar.',
      'Yüksek öncelikli görevleri gün başında kontrol edin.',
    ],
    related: ['Dashboard', 'Personel Mobil', 'Bildirim Merkezi'],
    keywords: ['görev', 'açık görev', 'tamamlandı', 'personel', 'öncelik'],
  },
  {
    id: 'bildirimler',
    title: 'Bildirim Merkezi',
    route: '/bildirimler',
    group: 'Operasyon',
    icon: 'Bell',
    summary: 'Sistem, görev, stok, sipariş, kampanya ve duyuru bildirimlerini yönetir.',
    purpose: 'Kullanıcıların önemli olayları kaçırmadan görmesini ve yöneticinin manuel bildirim göndermesini sağlar.',
    capabilities: [
      'Tüm, okunmamış, yüksek öncelik, sistem, görev ve sipariş bildirimlerini filtreleme.',
      'Bildirimleri okundu/okunmadı olarak takip etme.',
      'Tüm kullanıcılara, departmana, role veya tekil kullanıcıya bildirim gönderme.',
      'Bildirim türü, öncelik ve zamanlı gönderim ayarlarını kullanma.',
      'Bildirim ayarları üzerinden hangi bildirimlerin gösterileceğini düzenleme.',
    ],
    steps: [
      'Önce filtrelerden ilgili bildirim grubunu seçin.',
      'Okunmamış veya yüksek öncelikli bildirimleri önce değerlendirin.',
      'Manuel bildirim gönderecekseniz hedef kitlenin doğru olduğundan emin olun.',
      'Başlık ve mesajı kısa, anlaşılır ve aksiyon alınabilir yazın.',
      'Zamanlı gönderimde tarih ve saat bilgisini kontrol edin.',
    ],
    warnings: [
      'Yanlış hedef seçimi gereksiz kullanıcıya bildirim gitmesine neden olur.',
      'Yüksek öncelik yalnız gerçekten kritik durumlarda kullanılmalıdır.',
    ],
    tips: [
      'Bildirim türü, kullanıcının mesajı neden aldığını anlamasına yardımcı olur.',
      'Departman veya rol bazlı gönderim kalabalık mağaza ekipleri için daha düzenlidir.',
    ],
    related: ['Görev Planlama', 'Proximity Yönetimi', 'Personel Yönetimi'],
    keywords: ['bildirim', 'duyuru', 'okunmamış', 'öncelik', 'zamanlı gönderim'],
  },
  {
    id: 'personel-yonetimi',
    title: 'Personel Yönetimi',
    route: '/personel-yonetimi',
    group: 'Sistem Yönetimi',
    icon: 'Users',
    summary: 'Panel ve personel mobil uygulamasını kullanan personel hesaplarını yönetir.',
    purpose: 'Çalışanların doğru rol, departman ve erişimle sisteme giriş yapmasını sağlar.',
    capabilities: [
      'Yeni personel ekleme ve mevcut personeli düzenleme.',
      'Ad, kullanıcı bilgisi, rol, departman ve aktiflik durumunu takip etme.',
      'Personelin görev, bildirim ve sayfa erişimlerini dolaylı olarak yönetme.',
      'Hesap durumuyla giriş sorunlarını ayırt etme.',
    ],
    steps: [
      'Yeni personel eklerken ad, giriş bilgisi ve rol alanlarını eksiksiz girin.',
      'Departmanı doğru seçin; bildirim ve görev hedefleme ekranlarında bu bilgi kullanılabilir.',
      'Personel ayrıldıysa hesabı pasifleştirin.',
      'Yetki değişikliği gerekiyorsa Rol Yönetimi veya Erişim Talepleri ekranını kontrol edin.',
    ],
    warnings: [
      'Yanlış rol verilirse kullanıcı gereğinden fazla veya az ekran görebilir.',
      'Pasif hesaplar giriş veya işlem yapamayabilir.',
    ],
    tips: [
      'Personel adlarını gerçek mağaza kullanımına uygun tutmak görev atamayı kolaylaştırır.',
      'Yetki sorununda önce rolü, sonra erişim taleplerini kontrol edin.',
    ],
    related: ['Rol Yönetimi', 'Erişim Talepleri', 'Görev Planlama', 'Personel Mobil'],
    keywords: ['personel', 'kullanıcı', 'rol', 'departman', 'hesap'],
  },
  {
    id: 'musteri-yonetimi',
    title: 'Müşteri Yönetimi',
    route: '/musteri-yonetimi',
    group: 'Sistem Yönetimi',
    icon: 'UserCircle',
    summary: 'Müşteri hesaplarını ve müşteri portalı kullanımını izler.',
    purpose: 'Müşterilerin hesap, iletişim, sipariş ve bildirim deneyimini yönetici tarafında takip etmeyi sağlar.',
    capabilities: [
      'Müşteri kayıtlarını listeleme ve arama.',
      'Müşteri durumunu, iletişim bilgisini ve hesap bilgilerini kontrol etme.',
      'Müşteri portalı ve bildirim merkeziyle ilişkili sorunları anlamaya yardımcı olma.',
      'Şifre sıfırlama veya oturum sorunlarında müşteri kaydını doğrulama.',
    ],
    steps: [
      'Müşteriyi ad, telefon, e-posta veya diğer görünen bilgilerle arayın.',
      'Hesap durumunu ve iletişim bilgisini kontrol edin.',
      'Bildirim veya sipariş sorunu varsa müşterinin doğru hesapla giriş yaptığından emin olun.',
      'Gerekirse müşteri portalındaki hesap ve ayar adımlarını müşteriye tarif edin.',
    ],
    warnings: [
      'Müşteri kişisel bilgileri dikkatli kullanılmalıdır.',
      'Yanlış müşteri kaydında işlem yapmak destek sürecini uzatır.',
    ],
    tips: [
      'Bildirim şikayetlerinde müşteri ayarları ve Proximity Delivery Log birlikte değerlendirilmelidir.',
      'Şifre sıfırlama akışı müşteri giriş ekranından başlatılır.',
    ],
    related: ['Müşteri Portalı', 'Proximity Yönetimi', 'Bildirim Merkezi'],
    keywords: ['müşteri', 'müşteri hesabı', 'şifre sıfırlama', 'bildirim tercihi'],
  },
  {
    id: 'rol-yonetimi',
    title: 'Rol Yönetimi',
    route: '/rol-yonetimi',
    group: 'Sistem Yönetimi',
    icon: 'Shield',
    summary: 'Rolleri, departmanları ve sayfa/işlem yetkilerini yönetir.',
    purpose: 'Kullanıcıların yalnız görevleri için gerekli ekranlara erişmesini sağlar.',
    capabilities: [
      'Rol veya departman bazlı yetki düzenleme.',
      'Sayfa erişimi ve işlem izinlerini kontrol etme.',
      'Personelin neden bir sayfayı görmediğini açıklamaya yardımcı olma.',
      'Yetki değişikliklerinin güvenli şekilde yapılmasını sağlama.',
    ],
    steps: [
      'Rolü seçin ve hangi ekranlara erişmesi gerektiğini belirleyin.',
      'Gereksiz yetkileri kapalı tutun.',
      'Yetki değişikliğinden sonra ilgili kullanıcıdan çıkış/giriş yaparak kontrol etmesini isteyin.',
      'Erişim talebi geldiyse talep edilen sayfa ve gerekçeyi rol politikasıyla karşılaştırın.',
    ],
    warnings: [
      'Fazla yetki ürün, stok, fiyat veya sistem ayarlarında istenmeyen değişikliğe yol açabilir.',
      'Yetki değişiklikleri canlı kullanıcı deneyimini hemen etkileyebilir.',
    ],
    tips: [
      'Rol düzenlerken kişi bazlı değil görev tanımı bazlı düşünün.',
      'Geçici ihtiyaçlarda erişim talebi akışını kullanmak daha kontrollüdür.',
    ],
    related: ['Personel Yönetimi', 'Erişim Talepleri', 'Sistem Ayarları'],
    keywords: ['rol', 'yetki', 'permission', 'departman', 'erişim'],
  },
  {
    id: 'erisim-talepleri',
    title: 'Erişim Talepleri',
    route: '/erisim-talepleri',
    group: 'Sistem Yönetimi',
    icon: 'ShieldPlus',
    summary: 'Kullanıcıların göremedikleri sayfalar için oluşturduğu erişim taleplerini yönetir.',
    purpose: 'Yetki ihtiyacının yöneticiler tarafından kontrollü şekilde değerlendirilmesini sağlar.',
    capabilities: [
      'Kendi taleplerimi görme veya yönetici olarak tüm talepleri inceleme.',
      'Talep edilen sayfa, kullanıcı, gerekçe ve durum bilgisini takip etme.',
      'Talebi onaylama, reddetme veya beklemede bırakma.',
      'Yetki verilmişse kullanıcının ilgili sayfaya erişmesini sağlama.',
    ],
    steps: [
      'Kullanıcı bir sayfaya erişemediğinde Erişim Talebi Gönder aksiyonunu kullanır.',
      'Yönetici Erişim Talepleri ekranında talebin kimden geldiğini ve hangi sayfa için olduğunu okur.',
      'Gerekçe uygunsa talep onaylanır; uygun değilse reddedilir.',
      'Onay sonrası kullanıcı sayfayı tekrar açarak erişimi kontrol eder.',
    ],
    warnings: [
      'Talebi onaylamak kullanıcıya yeni işlem alanı açabilir; gerekliliği kontrol edin.',
      'Reddedilen taleplerde kullanıcıya anlaşılır gerekçe verilmesi destek yükünü azaltır.',
    ],
    tips: [
      'Admin kullanıcılarda Taleplerim menüsü gizli olabilir; yönetici tüm talepleri Erişim Talepleri ekranından izler.',
      'Sık gelen talepler rol tasarımının gözden geçirilmesi gerektiğini gösterebilir.',
    ],
    related: ['Rol Yönetimi', 'Personel Yönetimi', 'Sistem Ayarları'],
    keywords: ['erişim talebi', 'yetki isteği', 'talebim', 'onay', 'red'],
  },
  {
    id: 'sistem-ayarlari',
    title: 'Sistem Ayarları',
    route: '/sistem-ayarlari',
    group: 'Sistem Yönetimi',
    icon: 'Settings',
    summary: 'Mağaza, panel ve genel sistem davranışıyla ilgili ayarları yönetir.',
    purpose: 'Shelfio’nun işletme bilgileri, çalışma tercihleri, bildirim ve görünüm gibi yönetim ayarlarını düzenlemek için kullanılır.',
    capabilities: [
      'İşletme/panel bilgilerini kontrol etme.',
      'Mağaza çalışma saatleri ve genel kullanım ayarlarını düzenleme.',
      'Bildirim ve sistem tercihlerini yönetme.',
      'Destek, yasal metin veya ortak panel ayarlarını güncel tutma.',
    ],
    steps: [
      'Ayar değiştirmeden önce mevcut değerin hangi ekranları etkilediğini düşünün.',
      'İşletme adı, para birimi veya çalışma saatleri gibi alanları dikkatle güncelleyin.',
      'Değişiklikten sonra ilgili müşteri/personel ekranında görünümü kontrol edin.',
      'Sorun olursa son değiştirdiğiniz ayarı not edin.',
    ],
    warnings: [
      'Sistem ayarları birçok ekranı etkileyebilir; gereksiz değişiklik yapmayın.',
      'Gizli bilgi, şifre veya token gibi değerler son kullanıcı alanlarına yazılmamalıdır.',
    ],
    tips: [
      'Çalışma saatleri müşteri portalında gösterilen mağaza bilgisini etkileyebilir.',
      'Yetki gerektiren ayarları yalnız yönetici hesabıyla düzenleyin.',
    ],
    related: ['Rol Yönetimi', 'Bildirim Merkezi', 'Müşteri Portalı'],
    keywords: ['ayar', 'sistem', 'mağaza', 'çalışma saati', 'bildirim ayarı'],
  },
  {
    id: 'pos-kasa',
    title: 'POS / Kasa',
    route: '/pos-kasa',
    group: 'Satış',
    icon: 'ShoppingCart',
    summary: 'Kasa satış işlemleri için kullanılan POS ekranıdır.',
    purpose: 'Ürün okutma, sepet oluşturma ve satış işlemini tamamlama sürecini yönetir.',
    capabilities: [
      'Barkod veya ürün aramasıyla satış sepeti oluşturma.',
      'Ürün miktarını ve fiyatını kontrol etme.',
      'Satış işlemini tamamlama ve gerektiğinde iade akışını takip etme.',
      'Kasa yetkisi olmayan kullanıcıları POS PIN/giriş ekranıyla ayırma.',
    ],
    steps: [
      'Ürünleri barkodla okutun veya arayarak sepete ekleyin.',
      'Miktar, fiyat ve kampanya bilgisini kontrol edin.',
      'Ödeme alınmadan önce sepet toplamını müşteriyle doğrulayın.',
      'Satış tamamlandıktan sonra hata fark edilirse yetkili iade/düzeltme akışını kullanın.',
    ],
    warnings: [
      'Yanlış ürün veya miktar satışı stok ve kasa raporlarını etkiler.',
      'POS ekranı yetki gerektirir; PIN veya giriş ekranı çıkarsa yetkili kullanıcıyla devam edin.',
    ],
    tips: [
      'Barkod okunmuyorsa Barkod İşlemleri veya Ürünler ekranından ürün bilgisini kontrol edin.',
      'Kampanya fiyatı beklenenden farklıysa Kampanya Yönetimi ve ürün fiyatını karşılaştırın.',
    ],
    related: ['Barkod İşlemleri', 'Ürünler', 'Kampanya Yönetimi', 'Raporlar'],
    keywords: ['pos', 'kasa', 'satış', 'iade', 'barkod'],
  },
  {
    id: 'musteri-portali',
    title: 'Müşteri Portalı',
    route: '/musteri',
    group: 'Müşteri Deneyimi',
    icon: 'Smartphone',
    summary: 'Müşterinin ürün, sepet, kampanya, favori, hesap ve bildirim alanlarını kullandığı yüzeydir.',
    purpose: 'Müşterinin mağaza ürünlerini görmesini, kampanyaları takip etmesini ve proximity bildirimlerinden ürün detayına gitmesini sağlar.',
    capabilities: [
      'Ürün arama, kategori gezme ve ürün detayını görüntüleme.',
      'Sepet, favoriler, alışveriş listesi ve geçmiş siparişleri kullanma.',
      'Kampanyalar, popüler ürünler, hediye kartları ve mağaza çalışma saatlerini görme.',
      'Hesabım, ayarlar ve bildirim tercihlerini yönetme.',
      'Şifremi unuttum akışıyla müşteri hesabına tekrar erişme.',
    ],
    steps: [
      'Müşteri giriş yaptıktan sonra ürün arayabilir veya kategori sayfalarından gezebilir.',
      'Ürün detayında fiyat, kampanya ve ürün bilgilerini kontrol eder.',
      'Favori veya alışveriş listesine ekleyerek ürünü daha sonra bulabilir.',
      'Bildirim merkezinden gelen kampanya veya proximity bildirimlerini okuyabilir.',
      'Bildirimdeki Ürüne Git aksiyonu müşteriyi ilgili ürün detayına yönlendirir.',
    ],
    warnings: [
      'Müşteri bildirimleri, müşterinin izinleri ve bildirim tercihleri kapalıysa görünmeyebilir.',
      'Proximity bildirimi için customer uygulama/yüzeyi kullanılmalıdır; personel uygulamasında proximity hedeflenmez.',
    ],
    tips: [
      'Bildirim gelmiyor şikayetinde müşteri ayarları, oturum durumu ve Proximity Delivery Log birlikte kontrol edilmelidir.',
      'Şifre sıfırlama işlemi müşteri giriş ekranından başlatılır.',
    ],
    related: ['Müşteri Yönetimi', 'Proximity Yönetimi', 'Kampanya Yönetimi'],
    keywords: ['müşteri portalı', 'müşteri login', 'sepet', 'favoriler', 'bildirim tercihi', 'şifremi unuttum'],
  },
  {
    id: 'personel-mobil',
    title: 'Personel Mobil',
    route: '/personel',
    group: 'Personel Mobil',
    icon: 'TabletSmartphone',
    summary: 'Personelin mobil arayüzden görev, etiket, sipariş, lokasyon, sayım ve reyon besleme işlemleri yapmasını sağlar.',
    purpose: 'Saha personelinin bilgisayar başına geçmeden mağaza içinde operasyon yapmasını kolaylaştırır.',
    capabilities: [
      'Bildirimleri ve kendisine atanan görevleri görme.',
      'Etiket yönetimi işlemlerini sahada takip etme.',
      'Sipariş oluşturma, lokasyon yönetimi ve sayım işlemlerine erişme.',
      'Reyon besleme veya depo transfer talebi oluşturma.',
      'Görev detayına gidip durum takibi yapma.',
    ],
    steps: [
      'Personel hesabıyla giriş yapın.',
      'Ana ekranda size açık modülleri ve bildirimleri kontrol edin.',
      'Görevler ekranından atanan işleri inceleyin ve ilerleme durumunu güncelleyin.',
      'Sayım, lokasyon veya reyon besleme işlemlerinde ürün ve miktarı dikkatle seçin.',
      'İşlem sonunda panelde ilgili kayıt veya bildirim oluştuğunu kontrol edin.',
    ],
    warnings: [
      'Personel mobilde görünen ekranlar role ve yetkiye bağlıdır.',
      'Personel yüzeyi proximity müşteri bildirimi test etmek için kullanılmaz.',
    ],
    tips: [
      'Sahada barkod ve ürün adını birlikte kontrol etmek yanlış işlem riskini azaltır.',
      'Görev tamamlandığında durum güncellemek dashboard ve yönetici takibini doğru tutar.',
    ],
    related: ['Görev Planlama', 'Depo Transfer Talepleri', 'Etiket Yönetimi', 'Personel Yönetimi'],
    keywords: ['personel mobil', 'görevler', 'sayım', 'reyon besleme', 'lokasyon', 'etiket'],
  },
  {
    id: 'sik-sorunlar',
    title: 'Sık Karşılaşılan Sorunlar',
    route: '/nasil-kullanilir',
    group: 'Destek ve Kontrol',
    icon: 'ClipboardList',
    summary: 'Günlük kullanımda en sık görülen uyarı ve sonuç mesajlarını sade şekilde açıklar.',
    purpose: 'Kullanıcının teknik destek istemeden önce hangi ekrandan neyi kontrol edeceğini bilmesini sağlar.',
    capabilities: [
      'Bildirim gelmiyor, etiket güncellenmiyor veya ürün bulunamıyor gibi durumları ayırt etme.',
      'Proximity skip nedenlerini kullanıcı diliyle yorumlama.',
      'Geçersiz oturum, yetki eksikliği ve erişim talebi durumlarını anlama.',
      'Stok veya sipariş ekranlarında hata mesajını doğru modülle ilişkilendirme.',
    ],
    steps: [
      'Önce hatanın hangi ekranda çıktığını not edin.',
      'Ürün, cihaz, müşteri veya görev gibi ilgili kaydı arayıp gerçekten var ve aktif olduğunu kontrol edin.',
      'Yetki hatasında Erişim Talebi gönderin veya yöneticinizle görüşün.',
      'Proximity sorununda sırayla Etiket Yönetimi, Beacon, Yakınlık Alanı, Bildirim Kuralı, Event Log ve Teslimat / Cooldown ekranlarını kontrol edin.',
      'Sorun devam ederse hata mesajını, işlem saatini ve ilgili kayıt adını yöneticinize iletin.',
    ],
    warnings: [
      'Rastgele kayıt silmek veya pasifleştirmek sorunu büyütebilir; önce nedenini bulun.',
      'Proximity bildirimleri cooldown ve 12 saat ürün tekrar engeli nedeniyle hemen tekrar gelmeyebilir.',
    ],
    tips: [
      'UNKNOWN_BEACON cihaz eşleşmesi, NO_LINKED_ESL_DEVICE etiket bağlantısı, NO_LABEL_PRODUCT etikette ürün, NO_ACTIVE_DISCOUNT_FOR_LABEL_PRODUCT kampanya/indirim sorunu demektir.',
      'Geçersiz oturum mesajında çıkış yapıp tekrar giriş yapmak çoğu zaman ilk kontroldür.',
    ],
    related: ['Proximity Yönetimi', 'Etiket Yönetimi', 'Erişim Talepleri', 'Müşteri Portalı'],
    keywords: ['sorun', 'hata', 'bildirim gelmiyor', 'UNKNOWN_BEACON', 'NO_LABEL_PRODUCT', 'geçersiz oturum', 'yetki'],
  },
];

export const howToUseQuickActions = [
  {
    id: 'qa-product',
    title: 'Ürün ekle veya düzelt',
    guideId: 'urunler',
    description: 'Ürün kartını aç, kimlik, fiyat, stok ve yerleşim alanlarını kontrol et.',
    keywords: ['ürün', 'sku', 'barkod', 'fiyat'],
  },
  {
    id: 'qa-stock',
    title: 'Stok hareketi kontrol et',
    guideId: 'stok-islemleri',
    description: 'Ürün hareketlerini giriş, çıkış, transfer ve düzeltme olarak oku.',
    keywords: ['stok', 'hareket', 'transfer', 'sayım'],
  },
  {
    id: 'qa-esl-send',
    title: 'Etiket gönder',
    guideId: 'etiket-yonetimi',
    description: 'Ürün ve elektronik etiketi seç, önizlemeyi kontrol et, etikete gönder.',
    keywords: ['etiket', 'esl', 'elektronik etiket', 'gönder'],
  },
  {
    id: 'qa-proximity-setup',
    title: 'Proximity kur',
    guideId: 'proximity-yonetimi',
    description: 'Yakınlık Alanı oluştur, beacon ekle, ESL ve reyonla eşleştir, bildirim kuralı tanımla.',
    keywords: ['proximity', 'beacon', 'yakınlık alanı', 'bildirim kuralı'],
  },
  {
    id: 'qa-order',
    title: 'Sipariş hazırla',
    guideId: 'siparis-olustur',
    description: 'Tedarikçiyi ve ürünleri seç, miktarları kontrol et, sipariş akışına gönder.',
    keywords: ['sipariş', 'tedarikçi', 'satın alma'],
  },
  {
    id: 'qa-task',
    title: 'Görev ata',
    guideId: 'gorev-planlama',
    description: 'Görev başlığını yaz, personel ve son tarih seç, durumu takip et.',
    keywords: ['görev', 'personel', 'atama'],
  },
  {
    id: 'qa-permission',
    title: 'Yetki sorunu çöz',
    guideId: 'erisim-talepleri',
    description: 'Sayfa görünmüyorsa erişim talebini ve rol yetkilerini kontrol et.',
    keywords: ['yetki', 'erişim', 'rol', 'permission'],
  },
  {
    id: 'qa-troubleshoot',
    title: 'Sorun mesajını yorumla',
    guideId: 'sik-sorunlar',
    description: 'Proximity, etiket, oturum ve yetki uyarılarında ilk kontrol sırasını izle.',
    keywords: ['sorun', 'hata', 'UNKNOWN_BEACON', 'NO_LABEL_PRODUCT'],
  },
];
