export const howToUseGuides = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    route: '/anasayfa',
    group: 'Genel Bakış',
    icon: 'LayoutDashboard',
    summary: 'Mağaza operasyonunun KPI, uyarı, sipariş yaşam döngüsü, aktivite ve müşteri özetlerini tek ekranda izletir.',
    purpose: 'Günün operasyon durumunu hızlı okumak, riskleri fark etmek ve ilgili modüle tek tıkla geçmek için kullanılır.',
    capabilities: [
      'Erişim talepleri, stok, sipariş ve müşteri metriklerini özet kartlarda görüntüleme.',
      'Sipariş yaşam döngüsü panelinden sipariş takibine geçme.',
      'Kritik stok, yolda sevkiyat, geciken mal kabul, fiyat değişimi ve SKT uyarılarını ilgili sayfalara yönlendirme.',
      'Aktivite akışını açıp tarih aralığına göre filtreleme.',
    ],
    steps: [
      'Sayfayı açınca üst KPI kartlarını kontrol edin.',
      'Operasyonel uyarı kartlarından ilgili modüle geçin.',
      'Aktivite Akışı alanında Tümünü Gör seçeneğiyle detay modalını açın.',
      'Aktivite filtresinde başlangıç ve bitiş tarihini seçip Filtrele butonunu kullanın.',
    ],
    warnings: [
      'Dashboard özet amaçlıdır; veri düzeltme işlemleri ilgili modüllerden yapılır.',
      'Kritik uyarılar stok, sipariş ve tedarikçi verilerinin güncelliğine bağlıdır.',
    ],
    tips: [
      'Güne başlamadan önce Kritik Stok, Geciken Mal Kabul ve Yolda Olan Sevkiyat uyarılarını kontrol edin.',
    ],
    related: ['Stok İşlemleri', 'Sipariş Takibi', 'Raporlar', 'Erişim Talepleri'],
    keywords: ['anasayfa', 'genel bakış', 'kpi', 'uyarı', 'aktivite', 'müşteri özeti'],
  },
  {
    id: 'pos-kasa',
    title: 'POS / Kasa',
    route: '/pos-kasa',
    group: 'Satış',
    icon: 'ShoppingCart',
    summary: 'Günlük kasa operasyonlarını, satış/iade geçmişini ve gün sonu arşivini yönetir.',
    purpose: 'Kasa ekranına geçmek, satış/iade kayıtlarını incelemek, hızlı iade başlatmak ve gün sonu raporlarını arşivlemek için kullanılır.',
    capabilities: [
      'Günlük satış, iade ve kasa performansını izleme.',
      'Satış ve iade geçmişinde detay görüntüleme.',
      'Satış referansından iade ekranını açma.',
      'Gün sonu raporunu arşive ekleme; arşivde tarih, tutar ve genel arama filtreleriyle kayıt bulma.',
      'Arşiv ve gün sonu kayıtlarını PDF veya Excel olarak dışa aktarma.',
    ],
    steps: [
      'POS / Kasa sayfasında günlük özet kartlarını kontrol edin.',
      'Satış geçmişi veya iade geçmişi tablosunda Detay ile işlem satırını inceleyin.',
      'İade gereken satış için ilgili aksiyondan iade ekranını açın.',
      'Gün sonunda Gün Sonu alanından raporu açın ve Arşive Ekle butonunu kullanın.',
      'Arşiv modalında tarih veya tutar filtrelerini uygulayıp PDF/Excel dışa aktarımı kullanın.',
    ],
    warnings: [
      'Kasa satış ekranı ayrı /kasa akışıyla çalışır; POS merkezi raporlama ve geçiş noktasıdır.',
      'Gün sonu arşivlemeden önce iade kayıtlarının doğru işlendiğini kontrol edin.',
    ],
    tips: [
      'Arşivde Bugün ve Bu Hafta hızlı aralıkları yoğun günlerde kayıt bulmayı hızlandırır.',
    ],
    related: ['Raporlar', 'Kampanya Yönetimi', 'Müşteri Yönetimi'],
    keywords: ['pos', 'kasa', 'satış', 'iade', 'gün sonu', 'pdf', 'excel'],
  },
  {
    id: 'products',
    title: 'Ürünler',
    route: '/urunler',
    group: 'Ürün Yönetimi',
    icon: 'PackageSearch',
    summary: 'Ürün kartlarını listeleme, arama, filtreleme, detay inceleme, ürün ekleme ve düzenleme ekranıdır.',
    purpose: 'Ürün kimliği, kategori, lokasyon, fiyat, stok eşiği, lojistik ve etiket bilgilerini yönetmek için kullanılır.',
    capabilities: [
      'SKU, barkod, ürün adı, kategori veya tedarikçi ile arama.',
      'Ürün evreni, kategori, tedarikçi, durum, etiket ve reyon no filtreleriyle listeyi daraltma.',
      'Ürün detayını görüntüleme; aktif parti, stok, fiyat, FDT ve lojistik alanları inceleme.',
      'Yeni ürün ekleme veya mevcut ürünü düzenleme.',
      'Rastgele barkod üretme ve önerilen yerleşimi uygulama.',
      'Ürün silme işlemini onay modalı ile tamamlama.',
    ],
    steps: [
      'Filtreler bölümünde arama veya kategori/durum kriterlerini girin.',
      'Filtrele ile tabloyu daraltın; Temizle ile varsayılana dönün.',
      'Yeni Ürün butonuyla ürün formunu açın.',
      'Temel Bilgiler, Kategori ve Sınıflama, Yerleşim ve Planlama, Satış ve Durum, Lojistik Bilgi ve Etiketler bölümlerini doldurun.',
      'Kaydet ile yeni ürünü oluşturun veya tablo satırındaki Düzenle ile mevcut ürünü güncelleyin.',
    ],
    warnings: [
      'Barkod, SKU, ürün adı, marka, birim, kategori ve etiket alanları formda zorunlu akışların parçasıdır.',
      'Ürün silmeden önce stok, sipariş ve eşleşme etkilerini kontrol edin.',
    ],
    tips: [
      'Reyon no filtresi, lokasyon kaynaklı stok sorunlarını ürün listesinde hızlı yakalamaya yardım eder.',
    ],
    related: ['Kategoriler', 'Eşleşmeler', 'Stok İşlemleri', 'Etiket Yönetimi'],
    keywords: ['ürün ekleme', 'ürün düzenleme', 'barkod', 'sku', 'fiyat', 'stok eşiği'],
  },
  {
    id: 'categories',
    title: 'Kategoriler',
    route: '/kategoriler',
    group: 'Ürün Yönetimi',
    icon: 'Tags',
    summary: 'Kategori ve kategoriye bağlı ürün etiketlerini ayrı listelerde yönetir.',
    purpose: 'Mağaza ürün ağacını ve ürünlerde kullanılan etiket yapısını düzenlemek için kullanılır.',
    capabilities: [
      'Kategori listesinde kategori kayıtlarını görüntüleme, düzenleme ve silme.',
      'Etiket listesinde alt etiketleri görüntüleme, düzenleme ve silme.',
      'Yönetici rolünde Yeni Kategori ve Yeni Etiket oluşturma.',
      'Kategori formunda temel bilgiler ve görünürlük/durum alanlarını yönetme.',
    ],
    steps: [
      'Kategori Listesi veya Etiket Listesi bölümünü bulun.',
      'Yeni Kategori veya Yeni Etiket butonuyla formu açın.',
      'Temel bilgileri girip Kaydet butonunu kullanın.',
      'Mevcut satırda Düzenle ile kaydı güncelleyin.',
      'Sil aksiyonunda onay modalını kontrol ederek işlemi tamamlayın.',
    ],
    warnings: [
      'Kategori değişiklikleri ürün filtrelerini, müşteri mobil kategori görünümünü ve kampanya kapsamlarını etkileyebilir.',
    ],
    tips: [
      'Kampanya veya müşteri mobil düzeni hazırlamadan önce kategori isimlerini netleştirin.',
    ],
    related: ['Ürünler', 'Kampanya Yönetimi', 'Müşteri Mobil'],
    keywords: ['kategori', 'etiket', 'alt etiket', 'ürün etiketi'],
  },
  {
    id: 'suppliers',
    title: 'Tedarikçiler',
    route: '/tedarikciler',
    group: 'Tedarik & Satın Alma',
    icon: 'Truck',
    summary: 'Tedarikçi firmaları listeleme, filtreleme, ekleme, düzenleme ve silme ekranıdır.',
    purpose: 'Firma, yetkili, operasyon ve sistem metrikleriyle tedarikçi kartlarını yönetmek için kullanılır.',
    capabilities: [
      'Tedarikçi listesini filtreleme ve temizleme.',
      'Yeni Tedarikçi formunda firma bilgisi, yetkili, ek bilgiler ve sistem metriklerini girme.',
      'Tedarikçiyi düzenleme veya silme.',
      'Fiyat değişim analizi uyarılarından tedarikçi kayıtlarına geçme.',
    ],
    steps: [
      'Filtreler bölümünden tedarikçi listesini daraltın.',
      'Yeni Tedarikçi butonuyla formu açın.',
      'Firma Bilgisi, Yetkili, Ek Bilgiler ve Sistem Metrikleri alanlarını doldurun.',
      'Kaydet ile tedarikçiyi oluşturun.',
      'Listede Düzenle veya Sil aksiyonlarını kullanarak kaydı yönetin.',
    ],
    warnings: [
      'Tedarikçi silme veya pasifleştirme, sipariş oluşturma ve katalog eşleşmelerini etkileyebilir.',
    ],
    tips: [
      'Tedarikçi kartını oluşturduktan sonra ürün-tedarikçi eşleşmesini de kontrol edin.',
    ],
    related: ['Eşleşmeler', 'Sipariş Oluştur', 'Tedarikçi Kataloğu'],
    keywords: ['tedarikçi ekleme', 'firma', 'yetkili', 'supplier'],
  },
  {
    id: 'matches',
    title: 'Eşleşmeler',
    route: '/eslesmeler',
    group: 'Ürün Yönetimi',
    icon: 'Link2',
    summary: 'Ürün-tedarikçi, ürün-parti, ürün-depo ve ürün-reyon eşleşmelerini yönetir.',
    purpose: 'Satın alma, stok, depo ve reyon operasyonlarının doğru ürüne bağlanması için eşleşme kayıtlarını tutar.',
    capabilities: [
      'Son eşleşme değişikliklerini izleme.',
      'Ürün-tedarikçi, parti, depo ve reyon eşleşme listelerini ayrı filtrelerle daraltma.',
      'Yeni Eşleşme oluşturma.',
      'Eşleşme türüne göre ticari, parti, depo veya reyon alanlarını doldurma.',
      'Mevcut eşleşmeyi düzenleme.',
    ],
    steps: [
      'Eşleşmeler sayfasında ilgili eşleşme bölümünü seçin.',
      'Filtreler alanından ürün, tedarikçi, parti veya lokasyon kriteri girin.',
      'Yeni Eşleşme butonuyla formu açın.',
      'Eşleşme tipini seçin ve aktifleşen zorunlu alanları doldurun.',
      'Kaydet ile eşleşmeyi oluşturun veya listede Düzenle ile güncelleyin.',
    ],
    warnings: [
      'Eksik tedarikçi eşleşmesi sipariş oluşturma ve tedarikçi karşılaştırma akışını sınırlar.',
      'Depo/reyon eşleşmeleri stok hareketleri ve lokasyon yönetiminde görünür sonuç üretir.',
    ],
    tips: [
      'Tedarikçi katalog farklarını onaylamadan önce eşleşme durumlarını kontrol edin.',
    ],
    related: ['Tedarikçiler', 'Sipariş Oluştur', 'Lokasyon Yönetimi', 'Stok İşlemleri'],
    keywords: ['eşleşme', 'tedarikçi eşleşmesi', 'parti', 'depo', 'reyon'],
  },
  {
    id: 'barcode',
    title: 'Barkod İşlemleri',
    route: '/barkod-islemleri',
    group: 'Ürün Yönetimi',
    icon: 'ScanBarcode',
    summary: 'Barkod okutma veya manuel barkod aramayla ürünü bulup hızlı işlem başlatır.',
    purpose: 'Sahada ürünü barkodla tespit etmek ve stok giriş/çıkış gibi hızlı aksiyonlara ulaşmak için kullanılır.',
    capabilities: [
      'Kamera ile barkod okutma veya manuel barkod girme.',
      'Yeni Tarama ile akışı sıfırlama.',
      'Bulunan ürün için miktar ve açıklama girerek aksiyon onaylama.',
    ],
    steps: [
      'Barkod İşlemleri sayfasında tarama sekmesini veya manuel giriş alanını kullanın.',
      'Barkod numarasını okutun ya da girip Ara butonuna basın.',
      'Ürün bulunduğunda işlem kartını seçin.',
      'Miktar ve gerekiyorsa açıklama girin.',
      'Onayla ile işlemi tamamlayın.',
    ],
    warnings: [
      'Yanlış barkodla işlem yapmamak için ürün adını ve stok bilgisini kontrol edin.',
    ],
    tips: [
      'Yeni Tarama butonu bir sonraki ürün için ekranı hızla sıfırlar.',
    ],
    related: ['Ürünler', 'Stok İşlemleri', 'Personel Mobil'],
    keywords: ['barkod', 'okut', 'tarama', 'hızlı giriş', 'hızlı çıkış'],
  },
  {
    id: 'stock',
    title: 'Stok İşlemleri',
    route: '/stok-islemleri',
    group: 'Operasyon',
    icon: 'Boxes',
    summary: 'Stok giriş, çıkış, düzeltme, reyon besleme, imha, sayım ve hareket geçmişi akışlarını yönetir.',
    purpose: 'Ürünün fiziki ve sistem stoğunu operasyonel hareketlerle güncel tutmak için kullanılır.',
    capabilities: [
      'Sayfa Seçimi ile Stok Görüntüleme, Hareket Geçmişi, Stok İşlemleri ve Sayım görünümleri arasında geçme.',
      'Mal kabul ve parti girişinde sipariş veya manuel mod seçip kalem, parti no, SKT, depo lokasyonu ve kabul notu girme.',
      'Stok çıkışı, stok düzeltme, reyon besleme talebi, depo-reyon transfer talebi, stok imha ve sayım işlemleri yapma.',
      'İşlem öncesi bağlam panelinden anlık stok ve son hareketleri kontrol etme.',
      'Stok özeti ve hareket geçmişini arama, tip, sebep, lokasyon, kritik stok ve tükenmiş ürün filtreleriyle izleme.',
      'SKT geçmiş batch uyarılarını görme ve seçili geçmiş partileri imha akışına alma.',
      'Hızlı Barkod Girişi / Çıkışı modalını kullanma.',
      'Sayım arşivini sayfalama ile inceleme ve fark sonucunu doğrulama.',
    ],
    steps: [
      'Önce Sayfa Seçimi alanından Görüntüleme, Hareket, İşlem veya Sayım görünümünü seçin.',
      'İşlem görünümünde İşlem Tipi kartından mal kabul, çıkış, düzeltme, reyon besleme, transfer talebi veya imha akışını açın.',
      'Ürün, parti, lokasyon, miktar ve not alanlarını doldurun.',
      'İşlem Öncesi Bağlam alanında stok değerlerini kontrol edin.',
      'İlgili Kaydet, Talep Gönder veya Sayımı Kaydet butonuyla işlemi tamamlayın.',
      'SKT Geçmiş Ürün Uyarıları alanında tarihi geçmiş batch varsa seçip imha onayını tamamlayın.',
      'Sayım görünümünde fiziksel miktarı girdikten sonra fark uyarısını kontrol edip arşive düşen sonucu doğrulayın.',
    ],
    warnings: [
      'Mal kabul ve stok hareketleri yönetici yetkisi gerektirebilir.',
      'Stok düzeltme, hareket iptali ve imha işlemleri geri dönüşü zor operasyonel kayıtlardır; not alanını açıklayıcı doldurun.',
      'SKT geçmiş ürün imhasında ürün, parti ve miktar bilgisini onaydan önce tekrar kontrol edin.',
    ],
    tips: [
      'Sayım yaparken önce barkodla ürünü bulup mevcut depo/reyon değerlerini karşılaştırın.',
      'Transfer talebi oluştururken önerilen reyon kodu ve hedef doluluk bilgisini kontrol etmek fazla taşıma riskini azaltır.',
    ],
    related: ['Lokasyon Yönetimi', 'Sipariş Takibi', 'Raporlar', 'Barkod İşlemleri'],
    keywords: ['stok düzeltme', 'mal kabul', 'stok çıkışı', 'reyon besleme', 'transfer', 'stok hareketleri', 'skt geçmiş', 'imha', 'sayım'],
  },
  {
    id: 'location',
    title: 'Lokasyon Yönetimi',
    route: '/lokasyon-yonetimi',
    group: 'Operasyon',
    icon: 'MapPinned',
    summary: 'Reyon ve depo lokasyonlarını liste, grid ve detay panelleriyle yönetir.',
    purpose: 'Ürünlerin reyon/depo yerleşimini görmek, taşımak ve besleme taleplerini takip etmek için kullanılır.',
    capabilities: [
      'SKU, barkod, ürün, reyon/depo ve lokasyon kodu filtreleriyle arama.',
      'Reyon ve Depo görünümü arasında geçip ayrı özet kartları, gridleri ve liste tablolarını inceleme.',
      'Reyon Grid ve Depo Yerleşim Gridi üzerinden lokasyon seçme.',
      'Lokasyon detayından Reyon Besleme Talebi, Besleme Geçmişi, Göz Değiştir ve Ürün Taşı aksiyonlarını kullanma.',
      'Depo görünümünde lokasyon, stok, parti no ve SKT alanlarını birlikte kontrol etme.',
      'Ürün Taşı modalında taşıma talebi oluşturma.',
    ],
    steps: [
      'Üstteki Lokasyon Tipi alanından Reyon veya Depo görünümünü seçin.',
      'Filtreler bölümünde ürün, SKU, barkod veya lokasyon kodu arayın.',
      'Grid veya listeden lokasyonu seçin.',
      'Lokasyon Detayı panelinde ürün, stok ve gerekiyorsa parti bilgisini kontrol edin.',
      'Reyon tarafında Besleme Geçmişi veya Göz Değiştir; depo tarafında Ürün Taşı aksiyonunu kullanın.',
    ],
    warnings: [
      'Boş lokasyonda ürün taşıma aksiyonu devre dışı kalabilir.',
      'Lokasyon de?i?iklikleri personel mobil ve operasyon lokasyon deneyimini etkiler.',
    ],
    tips: [
      'Besleme geçmişi, tekrar eden reyon eksiklerini anlamak için iyi bir kontrol noktasıdır.',
    ],
    related: ['Stok İşlemleri', 'Personel Mobil', 'Müşteri Mobil'],
    keywords: ['lokasyon', 'reyon', 'depo', 'ürün taşı', 'göz değiştir', 'besleme'],
  },
  {
    id: 'warehouse-transfers',
    title: 'Depo Transfer Talepleri',
    route: '/depo-transfer-talepleri',
    group: 'Operasyon',
    icon: 'Route',
    summary: 'Depo/reyon transfer taleplerini operasyon kuyruğu olarak izleyen sayfadır.',
    purpose: 'Personel veya lokasyon akışlarından oluşan transfer taleplerinin durumunu takip etmek için kullanılır.',
    capabilities: [
      'Transfer taleplerini operasyon listesinde görüntüleme.',
      'Talebin kaynak/hedef, ürün ve durum bilgisini izleme.',
      'Depo ve reyon besleme süreçleriyle ilişkili kayıtları kontrol etme.',
    ],
    steps: [
      'Depo Transfer Talepleri sayfasını açın.',
      'Bekleyen veya işlemdeki talepleri ürün ve lokasyon bilgisiyle kontrol edin.',
      'İlgili operasyon tamamlandıktan sonra stok ve lokasyon ekranlarından sonucu doğrulayın.',
    ],
    warnings: [
      'Bu sayfa transfer akışlarını izler; stok miktarı düzeltmeleri Stok İşlemleri ekranından yapılır.',
    ],
    tips: [
      'Transfer yoğunluğu varsa Lokasyon Yönetimi ve Stok İşlemleri ekranlarını birlikte kontrol edin.',
    ],
    related: ['Lokasyon Yönetimi', 'Stok İşlemleri', 'Personel Mobil'],
    keywords: ['depo transfer', 'transfer talebi', 'reyon besleme'],
  },
  {
    id: 'supplier-products',
    title: 'Sipariş Oluştur',
    route: '/siparis-olustur',
    group: 'Tedarik & Satın Alma',
    icon: 'Wallet',
    summary: 'Ürün seçip tedarikçileri karşılaştırarak tekli veya toplu satın alma siparişi hazırlatır.',
    purpose: 'Ürün, tedarikçi, fiyat, MOQ, koli içi ve lojistik koşullarıyla sipariş taslağı oluşturmak için kullanılır.',
    capabilities: [
      'Ürün, SKU, kategori veya tedarikçi aramasıyla ürün seçme.',
      'Seçilen ürün için tedarikçi karşılaştırma panelini açma.',
      'Tedarikçi fiyat geçmişini ve eşleşme detaylarını inceleme.',
      'Sepete ürün ekleme, sepeti temizleme ve seçili ürünlerden sipariş hazırlama.',
      'Tekli sipariş veya tedarikçi bazlı toplu sipariş önizlemesi oluşturma.',
      'Sipariş notu ve tedarikçi notu girerek onaya gönderme.',
    ],
    steps: [
      'Ürün Seçimi alanında ürün adı, SKU veya barkodla arama yapın.',
      'Ürünü seçip Tedarikçi Karşılaştırma bölümünü inceleyin.',
      'Uygun tedarikçi satırından ürünü sepete ekleyin.',
      'Sepet alanında miktar ve koşulları kontrol edin.',
      'Siparişi hazırlayıp onaya gönderin veya toplu sipariş önizlemesini açın.',
    ],
    warnings: [
      'Ürün-tedarikçi eşleşmesi yoksa tedarikçi karşılaştırma ve sipariş oluşturma sınırlı kalır.',
      'MOQ, koli içi ve tedarikçi notları sipariş miktarını etkileyebilir.',
    ],
    tips: [
      'Toplu sipariş önizlemesi, farklı tedarikçilere ayrılan sepeti göndermeden önce kontrol etmeyi sağlar.',
    ],
    related: ['Eşleşmeler', 'Tedarikçiler', 'Sipariş Takibi', 'Sipariş Önerileri'],
    keywords: ['sipariş oluşturma', 'satın alma', 'tedarikçi karşılaştırma', 'sepet', 'onaya gönder'],
  },
  {
    id: 'supplier-catalog',
    title: 'Tedarikçi Kataloğu',
    route: '/tedarikci-urunleri',
    group: 'Tedarik & Satın Alma',
    icon: 'Database',
    summary: 'Tedarikçi ürün eşleşmeleri ve katalog görünümünü yönetir.',
    purpose: 'Tedarikçi ürün kartlarını, fiyatları, lojistik bilgileri ve katalog satırlarını düzenlemek için kullanılır.',
    capabilities: [
      'Tedarikçi seçerek katalog satırlarını görüntüleme.',
      'Sayfalama ve sayfaya git kontrolleriyle katalogda gezinme.',
      'Yeni Eşleşme oluşturma veya mevcut eşleşmeyi düzenleme.',
      'Ürün, tedarikçi, tedarikçi SKU, barkod, ticari bilgi ve lojistik alanları girme.',
      'Ürün Bilgisi, Fiyat Geçmişi ve Tedarikçi Karşılaştırma modallarını kullanma.',
    ],
    steps: [
      'Tedarikçi Kataloğu görünümünde tedarikçi seçin.',
      'Katalog satırlarını sayfalama ile inceleyin.',
      'Yeni Eşleşme veya Düzenle aksiyonuyla formu açın.',
      'Temel Bilgi, Ticari Bilgi ve Lojistik Bilgi bölümlerini doldurun.',
      'Kaydet ile eşleşmeyi güncelleyin.',
    ],
    warnings: [
      'Katalogdaki fiyat ve MOQ bilgileri sipariş oluşturma kararlarını doğrudan etkiler.',
    ],
    tips: [
      'Fiyat Geçmişi modalı, tedarikçi fiyat değişimlerini sipariş öncesi kontrol etmek için yararlıdır.',
    ],
    related: ['Sipariş Oluştur', 'Eşleşmeler', 'Tedarikçiler'],
    keywords: ['tedarikçi kataloğu', 'tedarikçi ürünleri', 'fiyat geçmişi', 'moq'],
  },
  {
    id: 'purchase-suggestions',
    title: 'Sipariş Önerileri',
    route: '/siparis-onerileri',
    group: 'Talep & Analiz',
    icon: 'Sparkles',
    summary: 'Stok, risk ve talep sinyallerinden satın alma önerileri üretir ve onaya gönderir.',
    purpose: 'Kritik stok, satış hızı ve tedarik koşullarına göre siparişe dönüştürülebilecek önerileri yönetmek için kullanılır.',
    capabilities: [
      'KPI, grafik, filtre paneli ve öncelik listesiyle önerileri değerlendirme.',
      'Ürün, SKU veya tedarikçi araması yapma.',
      'Durum, risk ve hızlı filtrelerle öneri listesini daraltma.',
      'Aktif/Arşiv görünümü arasında geçme.',
      'Öneriyi düzenleme, onaya gönderme veya reddetme.',
      'Seçili öneriler için toplu miktar düzenleme ve toplu siparişe gönderme.',
      'Öneri arşivinde uygulanan ve reddedilen kayıtları izleme.',
    ],
    steps: [
      'Filtre Paneli alanında arama, durum ve risk kriterlerini belirleyin.',
      'Aktif görünümde öneri satırlarını seçin.',
      'Tek satırda Düzenle ile miktarı güncelleyin veya Onaya Gönder aksiyonunu kullanın.',
      'Birden fazla satır seçtiyseniz Toplu Düzenleme veya Toplu Siparişe Gönder aksiyonunu kullanın.',
      'Arşiv bölümünde uygulanan ve reddedilen önerileri kontrol edin.',
    ],
    warnings: [
      'Onaya gönderme öncesinde tedarikçi eşleşmesi ve geçerli miktar kontrol edilir.',
      'Reddedilen öneriler arşiv akışına taşınır.',
    ],
    tips: [
      'Kritik risk ve takvim sinyali filtreleri, acil satın alma listesini hızla oluşturur.',
    ],
    related: ['Sipariş Oluştur', 'Sipariş Takibi', 'Fiyat & Talep Analizi'],
    keywords: ['sipariş önerisi', 'kritik stok', 'toplu sipariş', 'risk', 'onaya gönder'],
  },
  {
    id: 'purchase-orders',
    title: 'Sipariş Takibi',
    route: '/siparis-takibi',
    group: 'Tedarik & Satın Alma',
    icon: 'Receipt',
    summary: 'Satın alma siparişlerinin lifecycle durumlarını, onaylarını, mal kabulünü ve arşivini izler.',
    purpose: 'Siparişin oluşturulmadan tamamlanmaya kadar geçtiği operasyon aşamalarını yönetmek için kullanılır.',
    capabilities: [
      'Lifecycle performansı, gün bazlı sipariş hacmi, tedarikçi yoğunluğu ve bekleme grafikleriyle izleme.',
      'Sipariş no veya tedarikçi araması; tarih, durum, tutar ve kullanıcı filtreleri.',
      'Aktif Sipariş, Onay Bekleyen, Depoya Ulaşan/Giriş Bekleyen, Stok Girişi Bekleyen ve Arşiv listelerini inceleme.',
      'Sipariş detayını açma, PDF/Excel dışa aktarma.',
      'Yetkili kullanıcıyla Durum güncelleme, Mal Kabul Kararı verme veya siparişi iptal etme.',
    ],
    steps: [
      'Filtreler alanında sipariş no, tedarikçi, tarih veya durum kriteri seçin.',
      'İlgili listede Detay butonuyla sipariş snapshot, kalemler, finansal özet ve aktivite geçmişini inceleyin.',
      'Gerekiyorsa Durum aksiyonuyla yeni lifecycle aşamasını ve notu seçin.',
      'Depoya ulaşan siparişlerde Mal Kabul Kararı modalını kullanın.',
      'Stok girişi bekleyen kayıtları Stok İşlemleri ekranında tamamlayın.',
    ],
    warnings: [
      'Mal kabul ve manuel durum geçişleri yönetici yetkisi gerektirir.',
      'Lifecycle aşamasını değiştirirken sipariş bağlam özetini ve not alanını dikkatli kontrol edin.',
    ],
    tips: [
      'Bugün ve Son 7 Gün hızlı tarih filtreleri yoğun satın alma dönemlerinde listeyi daraltır.',
    ],
    related: ['Sipariş Oluştur', 'Stok İşlemleri', 'Raporlar'],
    keywords: ['sipariş takibi', 'mal kabul', 'durum güncelle', 'onay', 'arşiv'],
  },
  {
    id: 'pricing-analysis',
    title: 'Fiyat & Talep Analizi',
    route: '/fiyat-talep-analizi',
    group: 'Talep & Analiz',
    icon: 'BrainCircuit',
    summary: 'Ürünlerin fiyat, talep, stok, SKT ve risk sinyallerini analiz edip fiyat aksiyonları önerir.',
    purpose: 'İndirim, fiyat koruma veya kampanya aksiyonlarını veri sinyallerine göre yönetmek için kullanılır.',
    capabilities: [
      'Analizleri Yenile ile güncel sinyalleri çekme.',
      'Risk, SKT durumu, satış hızı ve öneri varlığına göre filtreleme.',
      'Akıllı filtre sekmeleri ve kritik filtre ile öncelikli ürünleri bulma.',
      'Tablo satırlarında öneri nedeni, marj, trend ve simülasyon bilgilerini inceleme.',
      'Satır seçip Toplu İndirim Uygula, Kampanyaya Ekle veya Fiyatı Koru aksiyonlarını kullanma.',
      'Toplu fiyat güncelleme modalında kapsam, ürün seçimi, uygulama türü ve önizleme doğrulaması yapma.',
    ],
    steps: [
      'Analizleri Yenile butonuyla veriyi güncelleyin.',
      'Fiyat Öneri Filtreleri alanında risk, SKT, satış hızı veya öneri filtresi seçin.',
      'Gerekirse Kritikleri Filtrele aksiyonunu kullanın.',
      'Tabloda ilgili ürünleri seçin.',
      'Toplu İndirim Uygula veya Kampanyaya Ekle aksiyonuyla işlem modalını açın.',
      'Önizleme ve risk uyarılarını kontrol edip Güncellemeyi Uygula butonunu kullanın.',
    ],
    warnings: [
      'Toplu fiyat değişikliklerinde marj riski ve geçersiz fiyat uyarılarını dikkate alın.',
      'Kampanyaya ekleme akışı Kampanya Yönetimi ile ilişkilidir.',
    ],
    tips: [
      'Öneri nedeni satır içi görünür; işlemden önce nedeni ve simülasyon indirimini karşılaştırın.',
    ],
    related: ['Kampanya Yönetimi', 'Ürünler', 'Raporlar'],
    keywords: ['fiyat analizi', 'talep analizi', 'toplu indirim', 'kampanyaya ekle', 'marj'],
  },
  {
    id: 'campaigns',
    title: 'Kampanya Yönetimi',
    route: '/kampanya-yonetimi',
    group: 'Talep & Analiz',
    icon: 'Megaphone',
    summary: 'Genel, ürün bazlı, kategori bazlı, marka bazlı, SKT bazlı ve satış bazlı kampanya akışlarını yönetir.',
    purpose: 'Kampanya kapsamı, indirim oranı, tarihleri, öneri listeleri ve simülasyon etkisini tek merkezden yönetmek için kullanılır.',
    capabilities: [
      'Genel, Ürün Bazlı, Kategori Bazlı, Marka Bazlı, SKT Bazlı ve Satış Bazlı kampanya görünümleri arasında geçme.',
      'Her görünümde o tipe ait aktif kampanya listesi ve kampanya arşivini görüntüleme.',
      'Kampanya adı, görünen ad, indirim oranı, tarih, hedef ürün/kategori/marka ve kapsam alanlarını düzenleme.',
      'Etki Simülasyonu ile indirim, marj, satış artışı, stok baskısı ve öneri etkisini kontrol etme.',
      'Kampanya Önerileri alanında sistemin analiz ve öneri motoruyla ürettiği adayları inceleme.',
      'SKT Fırsat Merkezi içinde SKT baskısı olan ürün sinyallerini, hızlı indirim önerilerini ve ürün listesini filtreleme.',
      'Satış Bazlı Kampanya Merkezi içinde yavaş satan ürün, stok baskısı, marj fırsatı ve satış hızı sinyallerini inceleme.',
      'SKT veya satış bazlı önerilerden Kampanya Oluştur aksiyonuyla kampanya taslağını doldurma.',
      'Hediye kartı oluşturma ve müşteriye hediye kartı atama.',
    ],
    steps: [
      'Kampanya Yönetimi sayfasında önce Genel, Ürün Bazlı, Kategori Bazlı, Marka Bazlı, SKT Bazlı veya Satış Bazlı görünümü seçin.',
      'Genel kampanyada tarih ve indirim bilgilerini; ürün, kategori veya marka bazlı kampanyada hedef kapsamı doldurun.',
      'SKT Fırsat Merkezi ve Satış Bazlı Kampanya Merkezi içinde öneri listesi ile ürün sinyallerini ayrı kartlarda inceleyin.',
      'Önerileri Yenile ve Filtreleri Temizle butonlarıyla listeyi güncel tutun.',
      'Simülasyon alanındaki marj, stok baskısı ve tahmini satış etkisini kontrol edin.',
      'Kampanyayı kaydedin veya öneri kartındaki Kampanya Oluştur aksiyonuyla taslağı otomatik doldurun.',
      'Hediye Kartı görünümünde kart oluşturup seçili müşteriye atayın.',
    ],
    warnings: [
      'Yüksek indirim oranları marj riskini artırır; simülasyon uyarılarını kontrol edin.',
      'Kampanya kapsamı müşteri mobil, POS fiyat görünümü ve etiket süreçlerini etkileyebilir.',
      'SKT ve satış bazlı öneriler karar desteği sağlar; kampanyayı yayınlamadan önce hedef ürünleri ve indirim oranını kontrol edin.',
    ],
    tips: [
      'SKT ve satış bazlı öneriler, kampanya kurmak için hazır kapsam ve gerekçe sağlar.',
      'Ürün, kategori ve marka kampanyalarında arama sonuçlarını daraltıp yalnız doğru hedefleri seçmek kampanyanın yanlış ürüne uygulanmasını önler.',
    ],
    related: ['Fiyat & Talep Analizi', 'Müşteri Yönetimi', 'POS / Kasa', 'Müşteri Mobil'],
    keywords: ['kampanya', 'indirim', 'hediye kartı', 'skt fırsat merkezi', 'satış bazlı kampanya merkezi', 'kampanya önerileri', 'kampanya listesi', 'ürün bazlı', 'kategori bazlı', 'marka bazlı'],
  },
  {
    id: 'reports',
    title: 'Raporlar',
    route: '/raporlar',
    group: 'Raporlama',
    icon: 'BarChart3',
    summary: 'Stok, ürün, hareket, sipariş, katalog ve operasyon raporlarını tarih aralığıyla sunar.',
    purpose: 'Operasyonel verileri denetlemek, dışa aktarmak ve bölüm bazlı rapor tablolarını incelemek için kullanılır.',
    capabilities: [
      'Başlangıç ve bitiş tarihi ile raporları filtreleme.',
      'Verileri Yenile ile raporları yeniden hesaplama.',
      'Bölüm bazlı tabloları sayfalama ile inceleme.',
      'Her rapor bölümü için Excel indirme.',
      'Ürün, stok hareketi, SKT, sipariş onay süreleri ve katalog fark raporlarını görüntüleme.',
    ],
    steps: [
      'Raporlar sayfasında tarih aralığını seçin.',
      'Filtreyi Uygula ile raporları güncelleyin.',
      'İlgili rapor bölümünde tabloyu inceleyin.',
      'Sayfalama kontrolleriyle kayıtlar arasında gezinin.',
      'Gereken bölümde Excel İndir butonunu kullanın.',
    ],
    warnings: [
      'Başlangıç tarihi bitiş tarihinden sonra olursa filtre uygulanmaz.',
      'Rapor verisi ilgili operasyon kayıtlarının doğruluğuna bağlıdır.',
    ],
    tips: [
      'Sipariş onay süreleri ve mal kabul raporları tedarik performansını takip etmek için birlikte okunabilir.',
    ],
    related: ['Dashboard', 'Stok İşlemleri', 'Sipariş Takibi', 'Tedarikçiler'],
    keywords: ['rapor', 'excel', 'stok raporu', 'sipariş raporu', 'katalog farkı'],
  },
  {
    id: 'tasks',
    title: 'Görev Planlama',
    route: '/gorev-planlama',
    group: 'Operasyon',
    icon: 'ClipboardList',
    summary: 'Operasyon görevlerini oluşturma, atama, filtreleme, tamamlama ve takip etme ekranıdır.',
    purpose: 'Personel görevlerini sistem içinde planlamak ve görev durumlarını izlemek için kullanılır.',
    capabilities: [
      'Yeni Görev Ekle formuyla görev oluşturma.',
      'Görevleri filtreleme ve görev listesinde görüntüleme.',
      'Satır aksiyonlarıyla görev detayını açma, düzenleme, silme veya tamamlandı durumunu değiştirme.',
      'Görev formunda atanan kullanıcı, durum ve açıklama alanlarını yönetme.',
    ],
    steps: [
      'Yeni Görev butonuyla görev formunu açın.',
      'Görev bilgilerini ve atanan kişiyi girin.',
      'Kaydet ile görevi oluşturun.',
      'Filtreler alanından görevleri daraltın.',
      'Görev Listesi satırında Detay, Düzenle veya durum aksiyonlarını kullanın.',
    ],
    warnings: [
      'Personel mobilde kullanıcı sadece kendisine atanmış görevlerde işlem yapabilir.',
    ],
    tips: [
      'Acil saha işleri için görev açıklamasına ürün, lokasyon ve öncelik bilgisini ekleyin.',
    ],
    related: ['Personel Mobil', 'Bildirim Merkezi', 'Stok İşlemleri'],
    keywords: ['görev', 'görev atama', 'tamamla', 'personel'],
  },
  {
    id: 'notifications',
    title: 'Bildirim Merkezi',
    route: '/bildirimler',
    group: 'İletişim',
    icon: 'Bell',
    summary: 'Bildirimleri filtreleme, okundu işaretleme, yeni bildirim oluşturma ve hedef kitleye göre izleme ekranıdır.',
    purpose: 'Sistem, personel ve müşteri iletişimini hedefli bildirimlerle yönetmek için kullanılır.',
    capabilities: [
      'Bildirim filtreleriyle listeyi daraltma.',
      'Bildirim satırını okundu işaretleme.',
      'Bildirim Oluştur modalında hedefleme, içerik ve ek seçenekleri doldurma.',
      'Bildirim ayarlarını görüntüleme.',
    ],
    steps: [
      'Bildirim Merkezi sayfasında filtreleri kullanın.',
      'Okunmamış satırda Okundu aksiyonunu kullanın.',
      'Yeni bildirim oluşturmak için Bildirim Oluştur akışını açın.',
      'Hedefleme ve İçerik bölümlerini doldurun.',
      'Gönder/Kaydet aksiyonuyla bildirimi tamamlayın.',
    ],
    warnings: [
      'Hedefleme yanlış seçilirse bildirim farklı kullanıcı grubuna gidebilir.',
    ],
    tips: [
      'Operasyonel görevlerde bildirim ve görev akışını birlikte kullanmak saha takibini kolaylaştırır.',
    ],
    related: ['Görev Planlama', 'Personel Mobil', 'Müşteri Yönetimi'],
    keywords: ['bildirim', 'okundu', 'hedefleme', 'mobil sipariş taslağı'],
  },
  {
    id: 'esl',
    title: 'Etiket Yönetimi / ESL',
    route: '/etiket-yonetimi',
    group: 'Etiket',
    icon: 'Monitor',
    summary: 'ESL cihazı ve ürün seçerek standart, fırsat veya indirim etiketini önizleyip cihaza gönderir.',
    purpose: 'Elektronik raf etiketlerini ürün verisi ve seçili şablonla cihazlara uygulamak için kullanılır.',
    capabilities: [
      'Barkod, QR, ESL cihaz ID veya MAC ile hızlı arama.',
      'Ürün ara panelinde SKU, ürün adı veya barkodla ürün seçme.',
      'Cihaz listesinden ESL cihazı seçme.',
      'Standart, Fırsat veya İndirim etiketi uygulama.',
      'Etiket önizlemesini kontrol edip Cihaza Gönder veya Etiketi Yeniden Gönder aksiyonlarını kullanma.',
      'Önizlemeyi temizleme ve seçili ürün/cihaz bilgisini sıfırlama.',
      'Gönderim geçmişini sayfalama ile izleme ve geçmişi temizleme.',
      'Mevcut etiketi temizleme onayıyla cihazdaki ürün atamasını kaldırma.',
    ],
    steps: [
      'Ürün Ara alanından ürünü seçin.',
      'Cihaz arama veya cihaz listesi üzerinden ESL cihazını seçin.',
      'Şablon seçimini standart, fırsat veya indirim olarak belirleyin.',
      'Önizleme alanında fiyat, FDT, barkod ve başlığı kontrol edin.',
      'Cihaza Gönder veya Etiketi Yeniden Gönder butonuyla etiketi gönderin.',
      'Gönderim Geçmişi bölümünden sonucu doğrulayın.',
      'Yanlış ürün seçtiyseniz önizlemeyi temizleyip ürün seçimini yeniden yapın.',
    ],
    warnings: [
      'Cihaz çevrimdışıysa gönderim butonu pasif kalabilir.',
      'Yanlış ürün-cihaz eşleşmesi raf etiketi hatasına yol açar; önizlemeyi mutlaka kontrol edin.',
      'Etiketi temizleme işlemi cihazın sonraki senkronizasyonda boş görünmesine neden olabilir.',
    ],
    tips: [
      'Fırsat ve indirim şablonları için fiyat ve FDT görünümünü göndermeden önce önizlemede kontrol edin.',
    ],
    related: ['Ürünler', 'Personel Mobil', 'Barkod İşlemleri'],
    keywords: ['etiket', 'esl', 'fırsat etiketi', 'indirim etiketi', 'cihaza gönder', 'etiketi yenile', 'etiketi yeniden gönder', 'ürün temizleme', 'önizleme temizle'],
  },
  {
    id: 'users',
    title: 'Personel Yönetimi',
    route: '/personel-yonetimi',
    group: 'Sistem Yönetimi',
    icon: 'Users',
    summary: 'Personel hesaplarını, rollerini, izinlerini, kasa atamalarını ve son aktivitelerini yönetir.',
    purpose: 'Sistem kullanıcılarını oluşturmak, güncellemek ve personel erişimlerini takip etmek için kullanılır.',
    capabilities: [
      'Personel filtreleriyle listeyi daraltma.',
      'Yeni Personel formuyla kullanıcı oluşturma.',
      'Personel düzenleme modunu açıp satır düzenleme/silme aksiyonlarını kullanma.',
      'Rastgele sicil no üretme.',
      'Personel Son İşlemleri modalında aktiviteyi filtreleme ve PDF/Excel dışa aktarma.',
    ],
    steps: [
      'Yeni Personel butonuyla formu açın.',
      'Kimlik, rol, yetki ve kasa bilgilerini doldurun.',
      'Kaydet ile personeli oluşturun.',
      'Düzenleme modunu açarak mevcut personeli güncelleyin.',
      'Son işlemler modalında aktiviteyi inceleyin veya dışa aktarın.',
    ],
    warnings: [
      'Personel yönetimi yönetici yetkisi gerektirir.',
      'Rol ve izin değişiklikleri kullanıcının menü görünürlüğünü ve işlem yetkilerini etkiler.',
    ],
    tips: [
      'Yeni personel oluşturduktan sonra Rol Yönetimi ve Erişim Talepleri akışını birlikte kontrol edin.',
    ],
    related: ['Rol Yönetimi', 'Erişim Talepleri', 'Personel Mobil'],
    keywords: ['personel', 'kullanıcı', 'rol', 'sicil', 'aktivite'],
  },
  {
    id: 'customers',
    title: 'Müşteri Yönetimi',
    route: '/musteri-yonetimi',
    group: 'Sistem Yönetimi',
    icon: 'UserCircle',
    summary: 'Müşterileri listeleme, detaylarını inceleme, bildirim gönderme, hediye kartı atama ve Excel dışa aktarma ekranıdır.',
    purpose: 'Müşteri profili, harcama özeti, sipariş geçmişi ve sadakat aksiyonlarını yönetmek için kullanılır.',
    capabilities: [
      'Müşteri listesinden seçim yapma ve detay modalını açma.',
      'Müşteri bilgileri, harcama özeti, sipariş geçmişi ve hediye kartı bilgisini görüntüleme.',
      'Tüm müşterilere veya seçili müşterilere bildirim gönderme.',
      'Seçili müşteriye hediye kartı atama.',
      'Müşteri listesini Excel olarak dışa aktarma.',
    ],
    steps: [
      'Müşteri Listesi bölümünde müşteriyi bulun.',
      'Satırdan müşteri detayını açın.',
      'Sipariş geçmişi ve hediye kartı bilgisini kontrol edin.',
      'Bildirim göndermek için hedef modunu seçin ve içerik alanını doldurun.',
      'Hediye Kartı Ata modalında aktif kartı seçip müşteriye atayın.',
    ],
    warnings: [
      'Hediye kartı atamak için tek müşteri seçimi gerekir.',
      'Bildirim içerikleri müşteri mobilde görünebilir; hedefi ve metni kontrol edin.',
    ],
    tips: [
      'Kampanya dönemlerinde müşteri segmentlerini bildirim ve hediye kartı aksiyonlarıyla birlikte kullanın.',
    ],
    related: ['Kampanya Yönetimi', 'Müşteri Mobil', 'Bildirim Merkezi'],
    keywords: ['müşteri', 'bildirim gönder', 'hediye kartı', 'sipariş geçmişi'],
  },
  {
    id: 'roles',
    title: 'Rol Yönetimi',
    route: '/rol-yonetimi',
    group: 'Sistem Yönetimi',
    icon: 'Shield',
    summary: 'Rolleri, rol kullanıcılarını ve modül izinlerini yönetir.',
    purpose: 'Kullanıcıların hangi modülleri görebileceğini ve hangi işlemleri yapabileceğini rol bazında düzenlemek için kullanılır.',
    capabilities: [
      'Yeni Rol Ekle formuyla rol oluşturma.',
      'Yeni Departman Ekle ile departman bazlı yetki kapsamı tanımlama.',
      'Rol listesinde kullanıcıları ve izinleri inceleme.',
      'Rol düzenleme formunda departman atamaları, yetki listesi ve modül detaylarını yönetme.',
      'Departman kurallarında role ek yetki verme veya rol yetkisini departman kapsamında kapatma.',
      'Kaydedilmemiş değişikliklerde uyarı modalı görme.',
    ],
    steps: [
      'Yeni Rol Ekle butonuyla rol formunu açın.',
      'Rol adı, açıklaması ve gerekiyorsa departman atamalarını girin.',
      'Yetki Listesi bölümünden izinleri seçin.',
      'Modül detaylarıyla izin kapsamını kontrol edin.',
      'Kaydet ile rolü oluşturun veya güncelleyin.',
      'Departman bazlı kapsam gerekiyorsa Yeni Departman Ekle ile genişletilen ve daraltılan yetkileri belirleyin.',
    ],
    warnings: [
      'Yanlış izin seçimi kritik sayfalara erişimi açabilir veya kapatabilir.',
      'Rol veya departman düzenlemeden önce bu kapsamdan etkilenen kullanıcıları kontrol edin.',
    ],
    tips: [
      'Operasyonel roller için yalnızca gereken modül izinlerini verin; departmanla açılan veya kapatılan yetkileri ayrıca kontrol edin.',
    ],
    related: ['Personel Yönetimi', 'Erişim Talepleri', 'Sistem Ayarları'],
    keywords: ['rol', 'yetki', 'izin', 'kullanıcı rolü', 'departman', 'departman bazlı yetki'],
  },
  {
    id: 'access-requests-admin',
    title: 'Erişim Talepleri',
    route: '/erisim-talepleri',
    group: 'Sistem Yönetimi',
    icon: 'ShieldPlus',
    summary: 'Kullanıcıların sayfa/işlem erişim taleplerini onaylama, reddetme, süre uzatma ve arşivleme ekranıdır.',
    purpose: 'Geçici veya kalıcı erişim ihtiyaçlarını kontrollü ve denetlenebilir şekilde yönetmek için kullanılır.',
    capabilities: [
      'Arama, durum, gerekçe ve tarih filtreleriyle talepleri daraltma.',
      'Bekleyen Talepler, Aktif Talepler ve Arşiv sekmeleri arasında geçme.',
      'Bekleyen satırda İncele, Onayla, Reddet ve Süre aksiyonlarını satır içinden kullanma.',
      'Aktif satırda kalan süreyi güncelleme veya erişimi iptal etme.',
      'Her sekmede bağımsız sayfalama ile kayıt aralığını izleme.',
      'Red ve süre güncelleme modallarında not girme.',
    ],
    steps: [
      'Filtreler bölümünde kullanıcı, gerekçe veya tarih aralığı seçin.',
      'Bekleyen Talepler sekmesinde satır içi İncele veya Onayla aksiyonuyla talebi açın.',
      'Uygunsa Onayla; uygun değilse Reddet aksiyonunu kullanın.',
      'Aktif Talepler sekmesinde Süre aksiyonuyla kalan erişim süresini güncelleyin veya İptal Et ile erişimi kapatın.',
      'Arşiv sekmesinde tamamlanmış kararları inceleyin.',
    ],
    warnings: [
      'Onaylanan erişim, ilgili kullanıcının menü ve işlem yetkisini etkiler.',
      'Red notunu anlaşılır yazmak kullanıcı geri bildirimi için önemlidir.',
    ],
    tips: [
      'Bugün Onaylanan KPI kartı günlük erişim yükünü takip etmek için hızlı bir sinyaldir.',
    ],
    related: ['Personel Yönetimi', 'Rol Yönetimi', 'Taleplerim'],
    keywords: ['erişim talebi', 'onayla', 'reddet', 'süre uzat', 'yetki'],
  },
  {
    id: 'my-access-requests',
    title: 'Taleplerim',
    route: '/erisim-taleplerim',
    group: 'Sistem Yönetimi',
    icon: 'ShieldPlus',
    summary: 'Kullanıcının kendi erişim taleplerini oluşturduğu ve durumlarını izlediği sayfadır.',
    purpose: 'Yetkisi olmayan bir sayfa veya işlem için gerekçeli erişim talebi göndermek için kullanılır.',
    capabilities: [
      'Yeni talep formunda yetki, süre ve gerekçe belirleme.',
      'Erişim Talep Et butonuyla talebi gönderme.',
      'Gönderilen taleplerin durumlarını tabloda izleme.',
    ],
    steps: [
      'Yeni Talep bölümünde yetkiyi ve süreyi seçin, ardından talep nedeninizi yazın.',
      'Erişim Talep Et butonuna basın.',
      'Talep tablosunda durum bilgisini takip edin.',
    ],
    warnings: [
      'Talep gerekçesi boşsa gönderim yapılamaz.',
      'Talebin onaylanması yönetici kararına bağlıdır.',
    ],
    tips: [
      'Gerekçede hangi sayfa ve hangi işlem için erişim gerektiğini açık yazın.',
    ],
    related: ['Erişim Talepleri', 'Rol Yönetimi'],
    keywords: ['taleplerim', 'erişim iste', 'gerekçe'],
  },
  {
    id: 'settings',
    title: 'Sistem Ayarları',
    route: '/sistem-ayarlari',
    group: 'Sistem Yönetimi',
    icon: 'Settings',
    summary: 'Mağaza, çalışma saatleri, kampanya/hediye kartı ilişkileri, bildirim, güvenlik ve log ayarlarını yönetir.',
    purpose: 'Platformun genel çalışma bilgilerini, destek iletişimini ve sistem davranışını yapılandırmak için kullanılır.',
    capabilities: [
      'Mağaza temel bilgileri, iletişim e-postası ve haftalık çalışma planını düzenleme.',
      'Tatil modu, özel günler ve lojistik tarife kayıtlarını yönetme.',
      'Kampanya, hediye kartı ve otomasyon merkezi ilişkilerini aynı sayfadan yönetme.',
      'Bildirim, ses ve güvenlik ayarlarını yönetme; test gönderimlerini çalıştırma.',
      'Son giriş aktiviteleri, audit log ve geliştirici loglarını filtreleme, dışa aktarma ve inceleme.',
      'Ayarları kaydetme.',
    ],
    steps: [
      'Sistem Ayarları sayfasında ilgili kartı veya kampanya görünümünü açın.',
      'Mağaza bilgileri, iletişim e-postası, çalışma saatleri veya operasyon seçeneklerini güncelleyin.',
      'Özel Gün eklemek için tarih, saat ve not alanlarını doldurun; gerekiyorsa Tatil Modu durumunu değiştirin.',
      'Kampanya / Hediye Kartı veya Otomasyon alanlarında gereken kayıtları güncelleyin.',
      'İzleme ve log kartlarında kayıtları filtreleyip inceleyin; gerekiyorsa test aksiyonlarını çalıştırın.',
      'Değişiklikleri Kaydet aksiyonuyla ayarları kaydedin.',
    ],
    warnings: [
      'Çalışma saati ve özel gün ayarları müşteri mobil mağaza bilgilerini etkiler.',
      'Güvenlik ve log ayarları sistem denetimi açısından kritik olabilir.',
    ],
    tips: [
      'Kampanya günü veya özel çalışma saatlerinde özel gün kayıtlarını önceden hazırlayın.',
    ],
    related: ['Kampanya Yönetimi', 'Bildirim Merkezi', 'Müşteri Mobil', 'İzleme ve Log Kayıtları'],
    keywords: ['ayarlar', 'mağaza', 'çalışma saatleri', 'özel gün', 'audit log', 'giriş aktiviteleri', 'geliştirici logları', 'gerçek veri'],
  },
  {
    id: 'monitoring-logs',
    title: 'İzleme ve Log Kayıtları',
    route: '/sistem-ayarlari',
    group: 'Sistem Yönetimi',
    icon: 'Database',
    summary: 'Sistem Ayarları içinde giriş aktiviteleri, audit kayıtları ve sistem loglarını izleme alanıdır.',
    purpose: 'Kimin ne zaman giriş yaptığını, hangi kritik işlemlerin kayda geçtiğini ve sistemde oluşan önemli kayıtları denetlemek için kullanılır.',
    capabilities: [
      'Son giriş aktivitelerini kullanıcı, tarayıcı ve tarih aralığına göre filtreleme.',
      'Audit kayıtlarında işlem, kullanıcı, sayfa veya tarih bilgisine göre inceleme yapma.',
      'Geliştirici loglarında hata, uyarı ve bilgi kayıtlarını filtreleme.',
      'Log detaylarını İncele aksiyonuyla açma.',
      'Uygun kayıtları Excel olarak dışa aktarma.',
      'Yetkili kullanıcı olarak manuel sistem kaydı oluşturma.',
    ],
    steps: [
      'Sistem Ayarları sayfasını açın.',
      'İzleme, log veya güvenlik kartlarından ilgili kayıt yönetimini açın.',
      'Kullanıcı, tarih, kaynak, hata tipi veya arama filtresini girin.',
      'Filtrele ile listeyi daraltın; Temizle ile varsayılan görünüme dönün.',
      'İncele butonuyla kayıt detayını açın veya Excel İndir ile listeyi dışa aktarın.',
    ],
    warnings: [
      'Bu alan denetim amaçlıdır; operasyon verisini düzeltmek için ilgili modül kullanılmalıdır.',
      'Log kayıtlarında teknik bilgiler olabilir, kullanıcıya gerekli olmayan ayrıntıları paylaşmayın.',
    ],
    tips: [
      'Yetki, giriş veya bildirim sorunlarında önce tarih aralığını daraltıp ilgili kullanıcıya göre filtreleyin.',
      'Sistem gerçek verilerle çalıştığı için rapor, log ve listelerde gördüğünüz kayıtlar işlem geçmişine bağlı olarak değişir.',
    ],
    related: ['Sistem Ayarları', 'Bildirim Merkezi', 'Rol Yönetimi', 'Erişim Talepleri'],
    keywords: ['izleme', 'log', 'log kaydı', 'audit', 'giriş aktiviteleri', 'sistem kaydı', 'hata kaydı', 'postgresql', 'gerçek veri'],
  },
  {
    id: 'customer-mobile',
    title: 'Müşteri Mobil',
    route: '/musteri',
    group: 'Mobil',
    icon: 'Smartphone',
    summary: 'Müşterinin ürün aradığı, kampanya gezdiği, sepet oluşturduğu, favori ve hesap işlemlerini yaptığı mobil deneyimdir.',
    purpose: 'Müşteriye ürün keşfi, kampanya, sepet ve hesap yönetimi sunmak için kullanılır.',
    capabilities: [
      'Ana sayfa, Ara, Kampanyalar, Sepet ve Hesabım alt navigasyonu.',
      'Ürün, marka, kategori veya barkod araması.',
      'Barkod okutma ve sesli arama butonları.',
      'Ürün detayında sepete ekleme, favoriye alma, mağaza/ürün durumu ve fiyat geçmişi görüntüleme.',
      'Sepette miktar artırma/azaltma, ürün kaldırma, alışveriş listesine ekleme ve siparişi tamamlama.',
      'Favoriler, alışveriş listem, hediye kartları, geçmiş siparişler, ayarlar ve yardım panelleri.',
      'Giriş gerektiren ekranlarda misafir koruması ve giriş/kayıt yönlendirmesi.',
      'Mağaza çalışma saatleri, popüler ürünler ve yardım/iletişim modallarını açma.',
    ],
    steps: [
      'Müşteri mobilde Ara sekmesine geçip ürün, kategori veya barkod arayın.',
      'Ürün kartından detaya girin veya doğrudan sepete ekleyin.',
      'Detayda favori ikonunu veya Sepete Ekle butonunu kullanın.',
      'Sepette miktarları kontrol edin ve Alışverişi Tamamla aksiyonunu seçin.',
      'Hesabım bölümünden favoriler, alışveriş listesi, hediye kartı, geçmiş sipariş ve ayarları yönetin.',
      'Ayarlar veya yardım gibi korumalı alanlarda giriş yönlendirmesi çıkarsa oturum açarak devam edin.',
    ],
    warnings: [
      'Favoriler, sipariş geçmişi ve ayarlar gibi kalıcı işlemler giriş gerektirebilir.',
    ],
    tips: [
      'Kampanya sekmesindeki Bugüne Özel ve Popüler filtreleri müşteri keşfini hızlandırır.',
    ],
    related: ['Kampanya Yönetimi', 'Müşteri Yönetimi', 'Lokasyon Yönetimi'],
    keywords: ['müşteri mobil', 'sepet', 'favori', 'kampanyalar', 'sipariş'],
  },
  {
    id: 'personnel-mobile',
    title: 'Personel Mobil',
    route: '/personel',
    group: 'Mobil',
    icon: 'TabletSmartphone',
    summary: 'Personelin görev, etiket, sipariş, lokasyon, reyon besleme, sayım ve bildirim işlemlerini mobilde yaptığı akıştır.',
    purpose: 'Saha operasyonlarını masaüstüne dönmeden hızlı tamamlamak için kullanılır.',
    capabilities: [
      'Ana ekranda ürün, SKU, kategori veya tedarikçi arama; barkod tarama.',
      'Alt navigasyondan Görevler, Etiket Yönetimi, Sipariş Oluştur, Lokasyon Yönetimi ve Reyon Besleme sayfalarına geçme.',
      'Sayım kısayolundan ürün bulup fiziksel miktarı kaydetme.',
      'Bildirimler ekranında bildirim arama, filtreleme, detay açma ve okundu işaretleme.',
      'Görevler ekranında görev arama, detay görme ve kullanıcıya atanmış görevi tamamlama.',
      'Etiket akışında ürün, cihaz, şablon seçip önizleme sonrası etiketi uygulama.',
      'Sipariş akışında ürünleri taslağa ekleyip taslakları onaya iletme.',
      'Lokasyon akışında reyon/depo kodu veya ürün arama.',
      'Reyon besleme talebinde kaynak/hedef lokasyon, miktar ve notla talep gönderme.',
    ],
    steps: [
      'Personel ana ekranında hızlı arama veya barkod tarama ile ürünü bulun.',
      'Alt navigasyondan yapacağınız işe uygun modülü seçin.',
      'Görevlerde Detay ile işi okuyun, uygunsa tamamlandı aksiyonunu kullanın.',
      'Etiket Yönetimi akışında ürün, cihaz, şablon ve önizleme adımlarını tamamlayıp Etiketi Uygula butonuna basın.',
      'Sipariş Oluştur akışında ürünü seçin, miktar girin, Taslağa Ekle ve Taslakları Onaya İlet butonlarını kullanın.',
      'Bildirimler ekranında kritik veya okunmamış kayıtları filtreleyip okundu olarak işaretleyin.',
      'Sayımda barkod/ürün arayın, fiziksel miktarı girip Sayımı Kaydet seçeneğini kullanın.',
    ],
    warnings: [
      'Personel mobilde bazı aksiyonlar sadece atanmış kullanıcıya veya yetkili role açıktır.',
      'Etiket ve sayım işlemlerinde yanlış ürün seçimi raf/stok verisini etkiler.',
    ],
    tips: [
      'Sahada etiket, lokasyon ve sayım işlerini barkod aramayla başlatmak hata payını düşürür.',
    ],
    related: ['Görev Planlama', 'Etiket Yönetimi / ESL', 'Stok İşlemleri', 'Lokasyon Yönetimi'],
    keywords: ['personel mobil', 'sayım', 'görev', 'etiket uygula', 'reyon besleme', 'taslak sipariş'],
  },
];

export const howToUseQuickActions = [
  {
    id: 'qa-product-create',
    title: 'Ürün ekleme',
    guideId: 'products',
    description: 'Ürünler sayfasında Yeni Ürün formunu açıp temel, kategori, yerleşim, satış ve etiket alanlarını doldurun.',
    keywords: ['ürün ekleme', 'yeni ürün', 'barkod üret'],
  },
  {
    id: 'qa-stock-adjust',
    title: 'Stok düzeltme',
    guideId: 'stock',
    description: 'Stok İşlemleri içinde Stok Düzeltme kartını seçip ürün, hedef miktar ve açıklama girin.',
    keywords: ['stok düzeltme', 'sayım farkı', 'stok'],
  },
  {
    id: 'qa-order-create',
    title: 'Sipariş oluşturma',
    guideId: 'supplier-products',
    description: 'Sipariş Oluştur ekranında ürünü seçin, tedarikçileri karşılaştırın, sepete ekleyin ve onaya gönderin.',
    keywords: ['sipariş oluşturma', 'satın alma', 'tedarikçi'],
  },
  {
    id: 'qa-campaign-start',
    title: 'Kampanya başlatma',
    guideId: 'campaigns',
    description: 'Kampanya türünü seçin, kapsam ve indirimi belirleyin, simülasyonu kontrol edip kampanyayı kaydedin.',
    keywords: ['kampanya', 'indirim', 'fırsat', 'ürün bazlı', 'kategori bazlı', 'marka bazlı'],
  },
  {
    id: 'qa-expiry-campaign',
    title: 'SKT fırsatı oluşturma',
    guideId: 'campaigns',
    description: 'SKT Fırsat Merkezi’nde ürün sinyallerini ve önerilen indirimi kontrol edip kampanya taslağı oluşturun.',
    keywords: ['skt fırsat merkezi', 'skt bazlı kampanya', 'kampanya önerisi'],
  },
  {
    id: 'qa-sales-campaign',
    title: 'Satış bazlı kampanya',
    guideId: 'campaigns',
    description: 'Satış Bazlı Kampanya Merkezi’nde satış hızı, stok baskısı ve marj sinyallerine göre önerileri inceleyin.',
    keywords: ['satış bazlı kampanya', 'satış fırsatları', 'yavaş satan ürün'],
  },
  {
    id: 'qa-task-assign',
    title: 'Görev atama',
    guideId: 'tasks',
    description: 'Görev Planlama ekranında Yeni Görev formuyla açıklama, atanan kişi ve durumu belirleyin.',
    keywords: ['görev atama', 'personel', 'operasyon'],
  },
  {
    id: 'qa-esl-send',
    title: 'Etiket gönderme',
    guideId: 'esl',
    description: 'Etiket Yönetimi’nde ürün ve cihaz seçip şablonu belirleyin, önizlemeyi kontrol ederek cihaza gönderin veya yeniden gönderin.',
    keywords: ['etiket gönder', 'esl', 'fırsat etiketi', 'etiket yenile', 'önizleme'],
  },
  {
    id: 'qa-goods-receipt',
    title: 'Mal kabul kaydı',
    guideId: 'stock',
    description: 'Stok İşlemleri’nde Mal Kabul ve Parti Girişi bölümünden sipariş, parti no, SKT ve miktarı girin.',
    keywords: ['mal kabul', 'parti girişi', 'skt'],
  },
  {
    id: 'qa-access-approve',
    title: 'Erişim talebi onaylama',
    guideId: 'access-requests-admin',
    description: 'Erişim Talepleri sayfasında bekleyen talebi inceleyin, uygun ise Onayla veya süre belirleyin.',
    keywords: ['erişim talebi', 'onay', 'yetki'],
  },
  {
    id: 'qa-log-check',
    title: 'Log kaydı inceleme',
    guideId: 'monitoring-logs',
    description: 'Sistem Ayarları içindeki log ve audit alanlarında kullanıcı, tarih veya hata tipine göre kayıtları filtreleyin.',
    keywords: ['log', 'audit', 'giriş aktivitesi', 'sistem kaydı'],
  },
];
